### ISSUE TITLE
I wanted to add a feature to the right of the picture display

### ISSUE THREAD

**Issue by WhiteML** [feimosi/baguetteBox.js#105]
- I wanted to add a feature to the right of the picture display, run a user-defined area, the contents of user-controllable. Mouseover effect or increase in the bottom of the title, the user can fill out a description.

- My English is very bad, these sentences Google translation, I hope you can understand.

**Comment by feimosi** [comment]
I'm not sure I can understand what you mean. If you want to add a custom template to the right of the picture, where the button is, then sorry, that's not possible.
You can only add your own markup in the image caption area.

**Comment by feimosi** [comment]
Hi @WhiteML, could you clarify this issue or should I close it?

**Comment by WhiteML** [comment]
sorry ,Recently I was considering doing a picture to explain. However, due to busy work, it delayed.
