### ISSUE TITLE
no ./src directory when `npm install baguettebox.js`

### ISSUE THREAD

**Issue by milose** [feimosi/baguetteBox.js#107]
Why is there no ./src directory when installing through npm?

**Comment by XhmikosR** [comment]
Because it's the src and not the dist files.

@feimosi: that is why I insisted we need to have a common dist folder with unminified files too.

**Comment by feimosi** [comment]
@milose as it was said, _src/_ is excluded from the npm package. Why do you need source code of your dependencies?

@XhmikosR will do that soon

**Comment by milose** [comment]
@feimosi I need it to include the scss files in to my main sass file:
```sass
@import 'node_modules/baguettebox.js/src/baguetteBox'
```
Then I can override classes and settings, without touching the original package :)

**Comment by feimosi** [comment]
@milose I understand, v1.6.3 should satisfy your needs  :)
