### ISSUE TITLE
photos not loading, while all is okay

### ISSUE THREAD

**Issue by neetfromrussland** [feimosi/baguetteBox.js#113]
Hi man! I created a simple gallery, like

```
<div id="photos">

<a href="images/image0009.jpg" ><img src="thumbnails/image0009.jpg"/></a>
<a href="images/image0010.jpg" ><img src="thumbnails/image0010.jpg"/></a>
<a href="images/image0011.jpg" ><img src="thumbnails/image0011.jpg"/></a>
<a href="images/image0012.jpg" ><img src="thumbnails/image0012.jpg"/></a>
<a href="images/image0013.jpg" ><img src="thumbnails/image0013.jpg"/></a>

 </div>
```

then i add lightbox

```
 <script src="baguetteBox.min.js"></script> 
 <script type="text/javascript">

baguetteBox.run('#photos', {
  animation: 'false',
});

  </script>
```

but it doesnt work correct. all files exist as they must be. but when i click next in lightbox, on 20 or something photo it doesnt load a photo. if wait like few minutes sometimes its load. but if i exit lighbox, and click on photo it immidiately opening in lightbox. in a second. but when i go back to lightbox and try to skip to this photo from prev photo or from next photo it doesnt show photo. so i just a bug. pelase man solve it. 

http://nikitaorlov.com/moscowtest/index.html

please check it. it occures multiple times on this page

**Comment by feimosi** [comment]
Hi, I've tried your website and everything works fine. No bugs, every image loads immediately. Tested on Chrome 51, 53 and Firefox 47. 
Could you be more specific about the environment? Make sure the HTML layout is correct and check the console for any error logs.

**Comment by neetfromrussland** [comment]
Man, i found the error! Thank for aasistance! I checked site for an errors, and saw some errors about photos that not loaded, while all seems loaded. So i went ot code and there was some old photos, that i deleted from site, physically, but forgot to delete them from code. So lightbox try to load them, but can't and wait till it load. 

Sorry for my mistake, though i wouldn' solve this without your help. great lightbox, its by now best i've seen. Maybe it better if lightbox would skip such photos? Anyway thanks man!!! Best lightbox!!! I'd only wish to improve touch interface on mobile phones, like if you click on it, then show next, and add in desktop version same, next photo by click (and prev by click in left side of photo). At least as an option, for more usefull and inyuative interface. Cause internet is using not only by young people but by old, and who not understand all new features fast, so i think it must be as an option. Anyway best gallery by now, from all galleries, great animation, design, and all. I'd change loading gif animation, but all other is perfect. Really best.

**Comment by feimosi** [comment]
I'm really glad you managed to resolve this issue. Also thanks for your suggestions! I'll consider each one individually. 
> is it way to make lightbox show 1st photo after last
This will be implemented in future releases.

VK has a really great lightbox for showing images, very robust, but also complex, and I've always strived for simplicity with baguetteBox.

Cheers :)
