### ISSUE TITLE
With multiple galleries one page gallery dont work proper

### ISSUE THREAD

**Issue by neetfromrussland** [feimosi/baguetteBox.js#116]
Hi Man! Here is the simple sample page http://nikitaorlov.com/images2/index3_2a2.html with multiple galleries on one page. First work normak, as it have to, but second doesn't work. I use simple code, as in manual same for both galleries. 

every gallery is simple div with photos. both is same. but first work fine and second not. also if add more galleries would work normal only first one

**Comment by neetfromrussland** [comment]
my mistake. i run baguettebox script twice, it was my mistake in code, sorry man

**Comment by feimosi** [comment]
Hey, no problem. I'm glad you've resolved your issue!
