### ISSUE TITLE
Possible code interaction?  "Uncaught RangeError: Maximum call"

### ISSUE THREAD

**Issue by jongarrison** [feimosi/baguetteBox.js#119]
Hi, I'm having fun with baguetteBox and trying to get it to work inside of NodeBB (a Node.js based forum).  I'm running into "Uncaught RangeError: Maximum call" in Chrome after a baguetteBox gallery is presented after a click.  The error happens on the click that brings up the gallery.

The errors are extensive (and seem to be related to a focus event getting retriggered), but these lines seem to keep looping by in Chrome:
d   @   baguetteBox.min.js?484233c5-6926-4ccd-b895-7bd20b1f99ac:7
ne  @   baguetteBox.min.js?484233c5-6926-4ccd-b895-7bd20b1f99ac:7
trigger @   nodebb.min.js?484233c5-6926-4ccd-b895-7bd20b1f99ac:5324

I'll keep trying to figure this out, as I think it is likely an interaction with other libraries, but has anyone seen any interaction problems like this between baguetteBox and other libraries?

**Comment by jongarrison** [comment]
I was able to stop the infinite loop by commenting out this one line:
https://github.com/jongarrison/baguetteBox.js/blob/dev/src/baguetteBox.js#L427

Something in NodeBB is fighting for focus.  Anyway, probably not a bug in baguetteBox.

**Comment by feimosi** [comment]
Yeah, that's really strange, but definitely can't be a baguetteBox issue. Let me know if you find a sensible workaround. 

Maybe you should report an issue in the NodeBB repo.

**Comment by jongarrison** [comment]
For my purposes, just commenting out that line in baguetteBox was sufficient.  If I have more time, I may come back and find the root of the interaction.

Thanks for the reply!  Great library!

**Comment by feimosi** [comment]
Thanks! I'm really glad you like baguetteBox.

**Comment by tbuckel** [comment]
Hi, I'm experiencing the same problem as @jongarrison in a pretty heavy-weight GWT app using bootstrap. 
Commenting out the call to initFocus() in showOverlay() does solve the problem, but I'm not 100% what the side effects are. @feimosi , do you think it's safe to comment it out?

Thanks

**Comment by feimosi** [comment]
I'm glad that helped! 
The `focus` part is about storing the focused element when gallery is being opened. This allows us to focus the element back when gallery closes.

**Comment by tbuckel** [comment]
Thanks. 
One suggestion: Exposing removeFromCache(selector) as public method would help SinglePageApps with multiple galleries.

**Comment by feimosi** [comment]
Well, you can currently use `baguetteBox.destroy()`, isn't this sufficient?

**Comment by huarxia** [comment]
ok,thanks


________________________________
发件人: Marek Grzybek <notifications@github.com>
发送时间: 2017年10月17日 8:04
收件人: feimosi/baguetteBox.js
抄送: Subscribed
主题: Re: [feimosi/baguetteBox.js] Possible code interaction? "Uncaught RangeError: Maximum call" (#119)


Well, you can currently use baguetteBox.destroy(), isn't this sufficient?

―

**Comment by tbuckel** [comment]
@feimosi, not in my case. I've got a  app which shows multiple galleries and also shows a different gallery in a popup triggered from that page. When the popup closes, I'd like to "destroy" (ie removeFromCache) the gallery which was shown in the popup without destroying the other galleries. Being a bit cautious about memory consumption there. I've done that on a fork and happy to do a pull request if you're interested.

BTW, great library!

**Comment by feimosi** [comment]
@tbuckel That's a fair point. I'll add this functionality in the v.2 👍

**Comment by tbuckel** [comment]
Thanks!

**Comment by pYr0x** [comment]
ran into the same issue with bootstrap modals. 
@feimosi comment out the `initFocus()` part solve the problem for me too.
is there any plan to add option to diable the init focus?

**Comment by feimosi** [comment]
@pYr0x I wish there was a better solution for that. Could you prepare some kind of jsFiddle with bootstrap so I could debug it myself first?

**Comment by pYr0x** [comment]
@feimosi http://jsfiddle.net/x1hphsvb/258/

**Comment by feimosi** [comment]
Thanks! I'll check it out when I have some time.

**Comment by feimosi** [comment]
I couldn't find a good fix on my side, but I'll probably add an option to turn off `focus` functionality in v2.0 aimed at such cases.

For now, if using Bootstrap, you can write:
```js
$.fn.modal.Constructor.prototype.enforceFocus = function () {};
```

Otherwise you have to comment out the `initFocus()` content,

Reference:
https://stackoverflow.com/questions/13649459/twitter-bootstrap-multiple-modal-error
