### ISSUE TITLE
API: progammable API?

### ISSUE THREAD

**Issue by bobylito** [feimosi/baguetteBox.js#121]
First thanks for the great job on this gallery. It is one of the best I've seen so far.

I'm trying to implement some url mechanism to track which photo is currently displayed and correctly handling the back button. Problem is I have a hard time manipulating the gallery programmatically. Currently I would need:
- open an image via its number
- switch to any image
- close the full width display of an image

What do you think? Would it be possible?

**Comment by feimosi** [comment]
I'm glad to hear that!

* if you mean opening a gallery on the specific image, that's a bit tricky thing to do as images are identified by a composite key (gallery ID, index). Much easier for now would be if you triggered basic `click()` event on desired thumbnail element.
* this can be done easily, supplementing `showNext`, `showPrevious` methods.
* do you mean simply closing the gallery? If so, this also can be done.

**Comment by bobylito** [comment]
0. well that's already what I'm currently doing, but this is convoluted. I need to store the number of the item, and when restoring the display of an image I need to find the image and then trigger the click. Click that won't trigger anything if the gallery is already open.
 0. Just using those methods requires work on my end. :)
 0. I mean doing what is done when afterHide is triggered. Right now I have to trigger a `click` on the overlay of the gallery.

What I expect from such an API would be:
 - `onChange` should provide all information needed to move to a given state
 - have a method `show` that would move the gallery and accept the previously given information
 - have a `close` that will be the opposite of show

As for the composite id, no issue here for me. I would either store both info or make a single out of that :)

**Comment by feimosi** [comment]
1. Sorry, I don't quite understand this use case. When you get a NodeList of images, each index should represent the nth image. I haven't tried that in practise, but seems straightforward.

> Click that won't trigger anything if the gallery is already open.

Is that a wrong behaviour?

2. I didn't mean using these methods, I just wanted to say that the proposed `show()` method is easy to implement :)
3. As above

`onChange`, what should this do? What kind of state?
`show`, previously given information? Do you mean this method should also open a gallery, right?
`close`, opposite of show in what way? Isn't it enough to just hide the gallery or what else do you need?

The problem with this `composite ID` is that the galleries are identified only by a reference to an array, something you can't access from the outside.
