### ISSUE TITLE
Look into publishing directly from master branch

### ISSUE THREAD

**Issue by XhmikosR** [feimosi/baguetteBox.js#123]
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch

**Comment by feimosi** [comment]
I've tried to use this approach, but eventually decided it's not suitable for this project. The main problem is, after every change I get two files updated (in `src/` and `docs/`) with the same changes which is not really convenient in `git` (`add`, `diff` etc.).

I'll leave the branch in case something changes in the future:
https://github.com/feimosi/baguetteBox.js/compare/docs-master-branch-publish
