### ISSUE TITLE
js/plugins.js Highlight.js 8.1, required?

### ISSUE THREAD

**Issue by xavierve** [feimosi/baguetteBox.js#125]
sorry I am newbie on JS
I have read the documentation and seams that only baguetteBox.js and its styles CSS are required.

But when a try the DEMO, (after adding distribution files) and playing with it, it ONLY WORKS with 
js/plugins.js (Highlight.js) on it.

So, is this plugin.js required to work?
thanks for supporting dummies >:)

**Comment by feimosi** [comment]
Hi, no, it's completely not related to `baguetteBox.js`. On the demo page it's being used to highlight the examples, that's all. With your own website you don't have to include it.

**Comment by xavierve** [comment]
Hi feimosi , thanks for your quick reply.
I have search on the web about that JS before posting for help,, and I have understood what you told me, BUT after trying I can't make it work without that plugins.jss
Should be something stupid ... I know  ... Could you PLEASE take a look to the url ?
with plugins.js [http://goo.gl/uuVyHE](url) is working
Without it , it doesn't [http://goo.gl/fthrt4](url)
IS THE Same code, just the plugins.js commented on 2nd url
will really appreciate your help!!

**Comment by feimosi** [comment]
Yes, that's because you've copied the whole `window.onload` code from the demo page. You should remove this part to make it working without the `plugins.js`:
```js
    if (typeof oldIE === 'undefined' && Object.keys) {
        hljs.initHighlighting();
    }
```

**Comment by xavierve** [comment]
that is !! removed and -obviously- working as a charm
thank you very much for your support
-sugestion: commenting code in DEMO would be good for dummies as (ejem) mi ´-
ps: thanks again for such a efficient piece of code !!--

**Comment by feimosi** [comment]
You're welcome. I'm glad you like my work :)
