### ISSUE TITLE
Support browsers that don't support SVG

### ISSUE THREAD

**Issue by jcubic** [feimosi/baguetteBox.js#126]
I have old Android phone with default browser that don't support svg and icons are not visible. It would be nice if baguetteBox check if svg is supported before using it.

**Comment by feimosi** [comment]
Hi, I've already got a fallback for SVG support:
https://github.com/feimosi/baguetteBox.js/blob/dev/src/baguetteBox.js#L162

The reason you don't see any buttons is because they are hidden on mobile devices by default. You may want to use `{ buttons: true }` option to enabled them.

**Comment by jcubic** [comment]
It work for prev/next but close is not visible.

**Comment by feimosi** [comment]
Ok, interesting, but I've got a clue, it may be caused by not closing the entity value here:
https://github.com/feimosi/baguetteBox.js/blob/dev/src/baguetteBox.js#L281
Can you change that line to:
`closeButton.innerHTML = supports.svg ? closeX : '&times;';`
and test it on your device?

**Comment by jcubic** [comment]
Yes it work.
