### ISSUE TITLE
Open lightbox with button? (Also latest JS is broken)

### ISSUE THREAD

**Issue by Limboistik** [feimosi/baguetteBox.js#127]
Hi there,

Love the lightbox and the fact that you can add multiple sources for responsive images!

Just one thing to make this perfect, is there a way to trigger the lightbox simply by having a button?

Like on Apple's site here to open the gallery:
http://www.apple.com/ca/shop/buy-watch/apple-watch/silver-aluminium-white-sport-band?preSelect=false&product=MNNG2CL/A&step=detail#

Click on "View Gallery" to see what I mean.

Please let me know, thanks!

**Comment by Limboistik** [comment]
Also the latest JS isn't initializing...it simply opens the image in a new window when you click, it's not calling the lightbox. Downloaded the .zip and simply opened up the demo HTML page, same issue.

**Comment by feimosi** [comment]
Hi, thanks for suggestion! I'll look into that in the future when I have more time.

Referring to your second issue, it's because the demo page is meant for development purpose, so the baguetteBox plugin file is generated dynamically by the build system.
If you want it working you should download the `baguetteBox.js.zip` file and paste its content in /js/ and /css subfolders correspondingly.

**Comment by rafhun** [comment]
The "View Gallery" button can be achieved already with the following markup (based on the markup in the readme file):
```
<div class="gallery">
  <a href="/path/to/first/image.jpg">View Gallery</a>
  <a href="/path/to/second/image.jpg"></a>
  <a href="/path/to/next/image.jpg"></a>
</div>
```

This might not be the nicest way to do it semantically, but it works. With some helper classes for the hidden gallery items, you could add describing text to them as well (View Gallery for all of them), then hide the text with CSS.

**Comment by feimosi** [comment]
It's now possible with the `ignoreClass` option - see description in the table: https://github.com/feimosi/baguetteBox.js#customization

```js
baguetteBox.run('.gallery', {
    ignoreClass: 'gallery-button'
});
```

```html
<div class="gallery">
    <a onclick="" class="gallery-button">View Gallery</a>
    <a href="img/2-1.jpg">
        <img src="img/thumbnails/2-1.jpg">
    </a>
    <a href="img/2-2.jpg">
        <img src="img/thumbnails/2-2.jpg">
    </a>
</div>
```

Assuming you bind an appropriate click handler.
