### ISSUE TITLE
Incorrect path to main files in bower.json

### ISSUE THREAD

**Issue by hrenly** [feimosi/baguetteBox.js#129]
In your bower.json file path is
`"main": [
    "./build/js/baguetteBox.js",
    "./build/css/baguetteBox.css"
  ],`
but now path is
`"main": [
    "./dist/baguetteBox.js",
    "./dist/baguetteBox.css"
  ],`

**Comment by feimosi** [comment]
Right, thanks for noticing!

**Comment by j-slvr** [comment]
please publish a new release with this fix
currently when you install baguettebox via bower the bug still comes with it.

**Comment by feimosi** [comment]
Done, sorry for delay.
