### ISSUE TITLE
diagnose? 

### ISSUE THREAD

**Issue by theskillwithin** [feimosi/baguetteBox.js#130]
Doesn't seem to be working:
```
import baguetteBox from 'baguettebox.js'
```
https://github.com/theskillwithin/chicevents/blob/master/src/assets/js/functions.js#L46

https://github.com/theskillwithin/chicevents/blob/master/src/gallery1.pug#L8

How do I diagnose this?

**Comment by theskillwithin** [comment]
```
window.baguetteBox = baguetteBox
```

```
baguetteBox.run('.gallery')   undefined   
```
https://i.imgur.com/3o5VH9V.png

and double checked,  .gallery does exist on the page.

**Comment by theskillwithin** [comment]
ahhaa figured it out I did not add the img href to the anchor tag.

**Comment by feimosi** [comment]
Great you figured it out :)
