### ISSUE TITLE
Double ESC to exit on Firefox

### ISSUE THREAD

**Issue by enricostano** [feimosi/baguetteBox.js#131]
I was just trying out the demo page: opening the slide show the focus lies on the `previous-button` element, or the `close-button` in the single image example.

Hitting `ESC` key just removes the focus from the element and you need an extra `ESC` to actually exit the slide.

Firefox version 50

**Comment by feimosi** [comment]
What OS do you use? Are there any errors in the console? Could you try it with all addons disabled (Safe Mode)? 
It works fine for me on Firefox v.50, Windows 10 machine.

**Comment by enricostano** [comment]
I'm on Linux but yeah, it's [VimFX](https://addons.mozilla.org/en-US/firefox/addon/vimfx/) that's intercepting the `ESC` hit.

Sorry for the noise and thanks for your time.

**Comment by feimosi** [comment]
No problem! I'm glad we've figured it out.
