### ISSUE TITLE
Mobile usability tweak

### ISSUE THREAD

**Issue by adamzea** [feimosi/baguetteBox.js#134]
I signed up for GitHub to say how awesome your baguetteBox.js script is!  Love it!  

The current one in the SRC folder doesn't work though, so I had to use the one that's used in the demo file. 
Also, I added a small tweak to baguetteBox.css that flips the location of the close button and caption when used on smartphones because people often hold phones with one hand and your thumb can't reach any buttons at the top of the screen. So for a better user experience, it's best to have the buttons in the middle to lower part of the screen. On desktops and wider screens, the X button remains at the top.

>>>
@media (max-width : 480px ){
	  .baguetteBox-button#close-button {
    top: auto;
	bottom: 20px;
     }
	 #baguetteBox-overlay .full-image figcaption {
      bottom: auto;
	  top: 0;
 }
}

**Comment by feimosi** [comment]
Thanks! I'm really glad you like it.

Could you please express in more detail what doesn't work? Are there errors in the console? I can't see any problems myself.

**Comment by adamzea** [comment]
Nevermind, it looks like the issue was that I was trying to use the files in the "src" folder and the SCSS wasn't compiling, when really I should have used the files in the "dist" folder. Stupid mistake (GitHub noob).  
Anyway, really like it... CSS was really easy to modify. Nicely done.

**Comment by feimosi** [comment]
Ok, great you've figured it out. Then I'm closing the issue.

**Comment by feimosi** [comment]
Actually, I forgot about the second part with close button placement, which I need to consider.

**Comment by feimosi** [comment]
After further consideration, I think the close button can stay as it is, because currently mobile users have two other options to close the lightbox:
- swipe the image up
- tap on the background overlay (e.g. below the image)

If it's not satisfactory everyone can add their custom styles to move the button to the bottom.
