### ISSUE TITLE
Infinite carousel

### ISSUE THREAD

**Issue by sqndr** [feimosi/baguetteBox.js#136]
Would it be possible to have an infinite carousel? So that when you're on the last slide and you click the next button, you go back to the first slide.

**Comment by feimosi** [comment]
Duplicate of #41.
Sorry, but currently it's not possible. I'm planning such a feature for the 2.0 release though.

**Comment by kavithakavithap** [comment]
Is there any updates on this feature?

**Comment by webmasterpf** [comment]
Hello,
I'm interesting in this feature too. any news about ?
Thanks
