### ISSUE TITLE
noScrollbars — Browser jumps to top

### ISSUE THREAD

**Issue by davidhellmann** [feimosi/baguetteBox.js#138]
Cool option but the first time after the page loads and I click on an image the page jumps to top. Maybe a much simpler Option would be to add a Body Class when the Box is open. Any Idea how I can fix that? What I set noScrollbars to false there is no jumping.

**Comment by feimosi** [comment]
Hi, thanks for your contribution!
I'm gonna replay here to your PRs altogether. When you take a look at the diff, it displays the whole `baguetteBox.js` file as changed. From what I've inspected the reason is that the indentation changed. Could you fix that?

**Comment by davidhellmann** [comment]
Hey! A friend talked to me the same. I edited it directly in github maybe that was the problem. I'm a bit busy today and tomorrow but here is my file with the changes from the PR (Indented with 2 Spaces): https://gist.github.com/davidhellmann/3ee10101ac4847360c1b2484664fd91a

Maybe that helps? :) If not I can edit the file next week.
Sorry :)

**Comment by feimosi** [comment]
Sure, it's not urgent. I just need the the proper indentation before it's merged into the codebase. Also seeing the changes on GitHub would be easier.
Anyway, take your time  :)

**Comment by feimosi** [comment]
Also if that's not a problem, please leave each PR only with its own changes (no PR 139 + 140 included). That's a cleaner way to manages projects and get my head around it.

**Comment by feimosi** [comment]
I think this was resolved in #143. Could check if the problem still occurs?
