### ISSUE TITLE
Problem: images link without extension.

### ISSUE THREAD

**Issue by makedonec88** [feimosi/baguetteBox.js#145]
Hi guys.

I'm using Amazon S3 as a storage for images.
The problem, that it's get you image links without extension, like this (same with lorem pixels and some other services):

[https://s3.eu-west-2.amazonaws.com/account-prod/2e94b1aa-0c88-438a-b5d1-5e38e6b2cbc9](https://s3.eu-west-2.amazonaws.com/account-prod/2e94b1aa-0c88-438a-b5d1-5e38e6b2cbc9)

It's work fine for setting images as  `img.src` or `background-image`. 

But unfortunately not working with **baguetteBox.js**, look like it's not recognize it as image.
Do you have any idea how to make it work ?

I made a pen with problem, where you can find regular aproach, and without extension (lorem pixel and amazon) - [link](http://codepen.io/makedonec88/pen/qrbwYo)

**Comment by feimosi** [comment]
Hello,
I think the solution to your issue is the `filter` option:
https://github.com/feimosi/baguetteBox.js#customization

So in you case you'd have to run the script e.g. like this:
```js
baguetteBox.run('.gallery', {
  filter: /.*amazonaws.*/i
});
```
or:
```js
baguetteBox.run('.gallery', {
  filter: /.*/i
});
```
to match every `<a>` tag,

See the new pen: http://codepen.io/anon/pen/mWPWXQ

**Comment by makedonec88** [comment]
@feimosi perfect. Thank you. Didn't think about filters this way.
