### ISSUE TITLE
Package folder name & node-sass

### ISSUE THREAD

**Issue by benavern** [feimosi/baguetteBox.js#146]
Hi!

I love baguetteBox.js and want to use it for one of my projects.

I am facing a problem with the folder name with a dot.

When installing with npm the package folder is `node_modules/baguettebox.js/` and that is fine for the js part (I use browserify).

For the styling part, I'd like to import the css in my project but here the dot makes it not working : 
my command is `node-sass --output-style=compressed --include-path=./node_modules/ src/sass/ -o dist/css/`

and in my app.sass I try to put 
```sass
@import 'baguettebox.js/dist/baguetteBox.css' 
```
but that doesn't work when that works for all the other third part libraries I use.
after some searchs I guessed it is because of the dot but still don't know how to fix it. 

Do you have an idea ? Could you rename the npm package ? 

Thank you though, it is very good work!

**Comment by feimosi** [comment]
Hi! 
I haven't encountered such error yet. Do you have the latest version of `node-sass` ? Dots in import paths should work by now (see: sass/libsass#280).
Also could you try dropping the `.css` extension from the import (see: [stackoverflow](http://stackoverflow.com/questions/7111610/import-regular-css-file-in-scss-file)) ?

**Comment by benavern** [comment]
I use `"node-sass": "^4.2.0"`, `node v6.9.4`, `npm v3.10.10`.

and both

```sass
@import 'baguettebox.js/dist/baguetteBox' // works
@import 'baguettebox.js/dist/baguetteBox.min' // also works
```
Thank you very much for the quick answere, I learnt something today! :-)

**Comment by feimosi** [comment]
You're welcome! Great I could help :)
