### ISSUE TITLE
Add <picture>-like WebP support

### ISSUE THREAD

**Issue by granttchart** [feimosi/baguetteBox.js#150]
Hiya. I've become accustomed to using a gulp task to auto-generate .webp files along with their .jpg counterparts in conjunction with the `<picture>` element so devices are served the most efficient file possible for the screen size. baguetteBox supports responsive images with the data-at attribute, but can't handle .webp files if the browser supports it.

**Comment by feimosi** [comment]
Hey, thanks for bringing this up! 
If I understand correctly, you'd like to achieve two separate things: 
- `<picture>` element support
- `.webp` image support

The latter already works by default with the `<img>` element, am I wrong?
I wish I could support `<picture>` but it's a complex element, and it seems tricky to parse it properly and display given responsive image.

**Comment by granttchart** [comment]
I worked on this a bit and put together a demo of baguetteBox with preliminary WebP support via new `data-webp-at-xxx` attributes. Needs a refactor for sure, but what do you think? 

`data-webp-at` attributes can co-exist with regular `data-at` options. If the browser supports WebP, the script prioritizes those options.

Additions: 
* testWebpSupport() at line 701. (Since the WebP test is asynchronous, it blocks further library execution for a brief moment.)
* new logic in getImageSrc() 

https://codepen.io/grantdotlocal/pen/mmWKMo

**Comment by feimosi** [comment]
Ok, now I understand. That seems like an unusual use case. I think it's more common to handle that server-side - based on the client's user agent you can serve either jpg or webp, without the frontend even knowing. Can you do that in you app?

Other solution would be to leave the `testWebpSupport` method and just replace file extension to `webp` if it's supported. Your solution is good too but it takes too much code and I always wanted baguetteBox to stay minimal and of as small size as possible.

**Comment by granttchart** [comment]
Thanks for your response! Unfortunately, user agent feature detection is notoriously unreliable, hence the rise of libraries like Modernizr which return detection booleans based on in-browser attempts to use the technology in question.

WebP [offers a substantial file size advantage](https://developers.google.com/speed/webp/faq#how_can_i_detect_browser_support_for_webp) and [its browser support is pretty good](http://caniuse.com/#search=webp). My current workflow is to run the source images through a gulp task using [gulp-responsive](https://github.com/mahnunchik/gulp-responsive), then deliver the best image to the user with `<picture>` markup like this (along with the [picturefill](https://github.com/scottjehl/picturefill) polyfill for older browsers):

```html
<picture>
<source type="image/webp" srcset="a-webp-file-1400px.webp" media="(max-width: 1400px)" />
<source type="image/jpeg" srcset="a-regular-old-jpeg-1400px.jpg" media="(max-width: 1400px)" />
<img src="old-browser-fallback.jpg" />
</picture>
```
This leaves the decision for which file to use up to the browser, but there's no way to take advantage of built-in `<picture>` functionality with the way baguetteBox sources are currently defined. 

Not sure I totally understand your suggestion — can you provide an example of that markup?

**Comment by cdowdy** [comment]
@granttchart 

> user agent feature detection is notoriously unreliable, hence the rise of libraries like Modernizr which return detection booleans based on in-browser attempts to use the technology in question.

When it comes to serving webp images to Blink based browsers you don't need to parse/sniff the User-Agent string. You can rely on using the Accept header since only browsers that "accept" webp images have that in the header.  

For instance Chrome/Opera show:  
``accept:image/webp,image/*,*/*;q=0.8``  

Firefox et all that don't show:  
``accept: */*``  

and edge:  
``Accept: image/png, image/svg+xml, image/jxr, image/*; q=0.8, */*; q=0.5``  

So after all that.. how do you serve webp to blink based browsers haha.. well here you go I wrote a post on this a while back and it has links to how to do this with apache if thats what you use https://corydowdy.com/blog/webp-jxr-nginx-content-negotiation-test

**Comment by feimosi** [comment]
@granttchart Sorry for my late reply. I really do know WebP is a great image format, superior to JPG and PNG, but I don't think it's lightbox script (or any other) responsibility to detect and serve appropriate images. If you were using 10 different plugins on your site, you probably wouldn't expect them all to handle this individually. It makes some extra code and bytes, which could be avoided.
As seen above, @cdowdy has proposed a great server-side solution for that. I'd also try the `Accept` header approach first.

I'll think about `<picture>`support in the future though.

**Comment by granttchart** [comment]
@feimosi I totally understand wanting to keep the library small and its features streamlined. But baguetteBox is already providing `<picture`>-like support in that it serves different image sizes depending on the screen size it detects.

It sounds like full `<picture>` support where baguetteBox merely displays the `<picture>` element and lets the browser figure out which image size/type to display would be the best next step, sidestepping custom code and relying on the standard ([which has good browser support!](http://caniuse.com/#search=picture)). Would you be interested in me working on a demo of that behavior?

**Comment by cdowdy** [comment]
@granttchart you don't need to modify baguettebox at all to support the picture element. You can grab the currentSrc of the picutre element then place what you told the browser to use in the ``href``  

Here's an example:  
```html  
<div class="gallery">
    <a id="galleryAnchor" href="http://www.gstatic.com/webp/gallery/1.webp">
        <picture id="pictureElement">
          <source type="image/webp"  
             srcset="http://www.gstatic.com/webp/gallery/1.webp" />
          <source type="image/jpeg" 
            srcset="http://www.gstatic.com/webp/gallery/1.jpg" />
          <img src="http://www.gstatic.com/webp/gallery/1.jpg" />
    </picture>
    </a>
</div>

<script>
  baguetteBox.run('.gallery');
  
  window.onload = function() {
    const picture = document.getElementById('pictureElement');
    const currentSource = document.getElementById('galleryAnchor');
    currentSource.href = picture.getElementsByTagName('img')[0].currentSrc;
  }
</script>
```    
Here's the working example from jsbin http://jsbin.com/cahucudowo/edit?html,output  

If you have a "gallery" then you would  need to adjust the example of getting the current source to fit your needs - removing the id's and use querySelector all like so:  

```html  
<div class="gallery">
  <a class="galleryAnchor" href="http://www.gstatic.com/webp/gallery/1.webp">
    <picture id="pictureElement">
      <source type="image/webp" srcset="http://www.gstatic.com/webp/gallery/1.webp" />
      <source type="image/jpeg" srcset="http://www.gstatic.com/webp/gallery/1.jpg" />
      <img src="http://www.gstatic.com/webp/gallery/1.jpg" />
    </picture>
   </a>

  <a class="galleryAnchor" href="http://www.gstatic.com/webp/gallery/2.webp">
    <picture class="pictureElement">
        <source type="image/webp" srcset="http://www.gstatic.com/webp/gallery/2.webp" />
        <source type="image/png" srcset="http://www.gstatic.com/webp/gallery/2.jpg" />
        <img src="http://www.gstatic.com/webp/gallery/2.jp" />
    </picture>
 </a>

  <a class="galleryAnchor" href="http://www.gstatic.com/webp/gallery/3.webp">
    <picture class="pictureElement">
        <source type="image/webp" srcset="http://www.gstatic.com/webp/gallery/3.webp" />
        <source type="image/png" srcset="http://www.gstatic.com/webp/gallery/3.jpg" />
        <img src="http://www.gstatic.com/webp/gallery/3.jpg" />
   </picture>
  </a>

  <a class="galleryAnchor" href="http://www.gstatic.com/webp/gallery/4.webp">
      <picture class="pictureElement">
          <source type="image/webp" srcset="http://www.gstatic.com/webp/gallery/4.webp" />
          <source type="image/png" srcset="http://www.gstatic.com/webp/gallery/4.jpg" />
          <img src="http://www.gstatic.com/webp/gallery/4.jpg" />
      </picture>
  </a>
 </div>

 <script>
    baguetteBox.run('.gallery');

    window.onload = function () {

    const currentSource = document.querySelectorAll('.galleryAnchor');

    currentSource.forEach(function (anchor) {
        let source = anchor.getElementsByTagName('img')[0].currentSrc;
        anchor.href = source;
    });
 }
</script>
```


Here is the live example of that http://jsbin.com/kolegeduhe/edit?html  


Using window onload might not be what you want this is just an example

**Comment by feimosi** [comment]
Thanks @cdowdy for this detailed example! I assume the issue is resolved 👍
