### ISSUE TITLE
TypeError: documentLastFocus is null 

### ISSUE THREAD

**Issue by ktomk** [feimosi/baguetteBox.js#151]
On baguette-box.js:472:9

on triggering the click event of the #close-button element via javascript and when the gallery never was activated before.

~~~
        var closeButton = document.getElementById('close-button');
        closeButton && closeButton.click();
~~~

**Comment by feimosi** [comment]
Thanks for reporting that, but in which scenario it can occur? I can't really imagine one, where you try to close the lightbox before it was ever opened.

**Comment by ktomk** [comment]
Scenario is a single page "app" in which I have some custom navigation via URL fragment hashes. When history back and forth buttons are used the click event is pro-actively triggered to close a (potentially) opened baguette-box.

Currently I'm running it patched like this: https://github.com/feimosi/baguetteBox.js/compare/dev...ktomk:patch-1#diff-4634650f8cf2cdceb34291a9bcf4c23f

**Comment by feimosi** [comment]
Ok, that makes sense. I'll patch it soon :+1:

**Comment by ktomk** [comment]
Great! I assume you don't need a PR for this otherwise just let me know.

**Comment by feimosi** [comment]
Fixed in 1cf4ec14fad4aa131a28414cb74a224f218e27c5

**Comment by ktomk** [comment]
Thanks! Will refresh the deps on next website update!

**Comment by feimosi** [comment]
You're welcome!
