### ISSUE TITLE
Specify MIME type In arguments

### ISSUE THREAD

**Issue by DanielSokil** [feimosi/baguetteBox.js#153]
Getting Error baguetteBox.js wont run.
![selection_002](https://user-images.githubusercontent.com/24403355/28584956-a337bd30-713c-11e7-9ac6-2ef7f094c084.png)

Is there a way to specify MIMI type in arguments, Similiar to fancybox ?

`$(".fancybox").fancybox({
   "type": "image"
});
`

**Comment by feimosi** [comment]
Could you provide more information? I can't reproduce how this issue is coming up. Isn't this something connect to a backend response and the `content-type` field?

**Comment by XhmikosR** [comment]
I think this is an issue with the server an unrelated to this.

**Comment by feimosi** [comment]
I think that too.
@DanielSokil could you provide more information? Otherwise I'll close it within a few days.
