### ISSUE TITLE
manual/cdn including not working

### ISSUE THREAD

**Issue by cutelittleturtle** [feimosi/baguetteBox.js#156]
I have tried both manual/cdn including css/js in my html but I do not get gallery. I have 3 images showing up from top to bottom.

The code looks like this: I also tried putting both css and js within <body> tag, right before the function call.

```
<head>
...
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.9.0/baguetteBox.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.9.0/baguetteBox.min.css">
</head>

<body>
...
baguetteBox.run('.gallery');
                                                                                                                       
<!-- testing gallery -->
<div class="gallery">
    <a href="img1.jpg" data-caption="Image caption">
            <img src="img1.jpg" alt="First image">
                </a>
    <a href="img2.jpg" data-caption="Image caption">
            <img src="img1.jpg" alt="First image">
                </a>
   <a href="img3.jpg" data-caption="Image caption">
            <img src="img1.jpg" alt="First image">
                </a>
</div>

...
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.9.0/baguetteBox.js"        async></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.9.0/baguetteBox.min.js"    async></script>
</body>
```

The result looks like this: apparently the function call is not treated like a function...
![image](https://user-images.githubusercontent.com/31291893/30848006-2dc9859e-a263-11e7-9d97-95d17f0738f7.png)

I am using Hexo:3.39
Theme: hexo-next
hexo-cli: 1.0.3
markdown parser: marked

**Comment by feimosi** [comment]
`baguetteBox.run` should be placed inside the `<script>` tag, just like this:

```html
<script>
baguetteBox.run('.gallery');
</script>
```

**Comment by feimosi** [comment]
Well, you should run the code when DOM is ready:
```html
<script>
document.addEventListener('DOMContentLoaded', function() {
  baguetteBox.run('.gallery');
});
</script>
```

**Comment by cutelittleturtle** [comment]
Hi thank you so much for helping out!

Right now I am doing exactly as you said but I still did not see any signs that the plugin has been activated. For convenience  I put all things in <body> this time.

Is it possible that the theme's default image processor just overwrites whatever the plugin tries to do? I check the generated page source, which looks exactly like the original source.

```
<p><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.9.0/baguetteBox.min.css"></p>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.9.0/baguetteBox.css">


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.9.0/baguetteBox.min.    js" async></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.9.0/baguetteBox.    js" async></script>

<script>
document.addEventListener('DOMContentLoaded', function() {
  baguetteBox.run('.gallery');
  });
</script>

<!-- testing gallery -->
<div class="gallery"><br>    <a href="img1.jpg" data-caption="Image caption"><br>            <img src="img1.jpg" alt="First image"><br>                </a><br>    <a href="img2.jpg" data-caption="Image caption"><br>            <img src="img1.jpg" alt="First image"><br>                </a><br>   <a href="img3.jpg" data-caption="Image caption"><br>            <img src="img1.jpg" alt="First image"><br>                </a><br></div>
```

**Comment by feimosi** [comment]
@cutelittleturtle Alright, I didn't notice the script is loaded as `async`, then you have to use `load` event:
```html
<script>
window.addEventListener('load', function() {
  baguetteBox.run('.gallery');
});
</script>
```

**Comment by feimosi** [comment]
Did that help?

**Comment by cutelittleturtle** [comment]
@feimosi yeah this time it works! tit looks beautiful. hank you very much! So I have also tried load baguatte without `async and the `document.addEventListener`, it does not work. 

But the plugin seems to overlay with the default lightbox effects. I am not sure if this is something that I need to fix on the hexo's side though. 

By the way may I ask what you did to get the gallery/grid displaying for pictures in your demo? I suppose that is not a function of this plugin ?

**Comment by feimosi** [comment]
> But the plugin seems to overlay with the default lightbox effects. 
I don't quite understand. Could you provide a screenshot?

The gallery grid on the demo page is my custom CSS, no 3rd-party library.

**Comment by cutelittleturtle** [comment]
yes. if you would be so kind to go to this [link](https://cutelittleturtle.github.io/2017/09/07/ybysource/) and click on the picture, you will see what I mean by overlaying.

**Comment by feimosi** [comment]
Ok, I see what you mean, but none of these is baguetteBox, there are two different lightboxes: lightGallery and fancyBox.

**Comment by cutelittleturtle** [comment]
i see. so i guess i have to find a way to disable fancyBox. I really hope Hexo's plugin system works more like those WP where one plugin will replace another instead of adding together lol. 

Hey thank you very much for walking me through these problems; i really appreciate your help.

**Comment by feimosi** [comment]
No problem, I hope you'll find a way to integrate baguetteBox with Hexo.
If it needs some extra code, write a comment here so other people will know what to do.

**Comment by cutelittleturtle** [comment]
I think the above ones are good. The only inconvenient part is that the users must figure out how to disable whatever lightbox feature that comes with their themes. For **Next** , it's easy, just turn it off in _config.yml. For **landscape**, need to go to `themes/lanscape/source/js/script.js` and comment out `fancybox` functions.

**Comment by Jeevan9819** [comment]
Why it is not working in. Ajax call?
