### ISSUE TITLE
Left/Right buttons not appearing on Firefox Developer Edition 57.0b3 (64-bit) Linux

### ISSUE THREAD

**Issue by DenialAdams** [feimosi/baguetteBox.js#157]
Version tested: 1.9.1

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0. Desktop. The buttons show up fine in chrome; same system.

The left and right buttons are in the DOM, but with display: none as the style. I tried forcing buttons on with buttons: true, but to no avail.

Thanks for your work on this; I'll try and take a look myself if I have time.

**Comment by DenialAdams** [comment]
Ok, sorry, I totally lied! buttons: true does get them to show up. Going to try and see why auto turns them off

**Comment by DenialAdams** [comment]
Ok, `"ontouchstart" in window` is returning true.

Seems like this is an issue on my end, and might be related to development tools (although I have never used responsive mode, as far as I know, and I just installed Firefox Dev Edition today.)

My about:config reports `dom.w3c_touch_events.enabled;2` which is default (auto-detect) so I don't know why it is reporting that as true.

Anyway, your code looks totally reasonable so I'm going to go ahead and close this as it's a client issue. Thanks for all your work!
Potentially useful reading:
https://github.com/Modernizr/Modernizr/issues/1731
https://stackoverflow.com/questions/21426962/firefox-on-windows-8-reporting-as-a-touch-device
https://github.com/twbs/bootstrap/issues/13748
https://bugzilla.mozilla.org/show_bug.cgi?id=970346

**Comment by feimosi** [comment]
Thanks for reporting that! Maybe you're using a touchscreen laptop? If not have you tried on normal version of Firefox? Otherwise it's indeed a browser issue and I can't help here.
