### ISSUE TITLE
Not working with Vue.js

### ISSUE THREAD

**Issue by leonardo-sj** [feimosi/baguetteBox.js#158]
The code above is not working.
There is no error message.
How to use baguetteBox.js with Vue.js ?

```
  <script>
    var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!',
    items: []
  },
   mounted(){
    this.$nextTick(function () {
      baguetteBox.run('.gallery');
    });
   }
})
</script>
```

**Comment by feimosi** [comment]
Are you sure at the time of `baguetteBox` invocation there are `..gallery` elements in the DOM?
Could you provide more context? Preferably put it in this environment: 
https://codesandbox.io/
so I could easily debug it.

**Comment by leonardo-sj** [comment]
According to Vue.js documentation, this.$nextTick() in mounted() method is called after the DOM is complete.
https://vuejs.org/v2/api/#mounted

I didn't find simple HTML editor in codesandbox, so I used JSFiddle.
https://jsfiddle.net/nd5jupe3/

**Comment by feimosi** [comment]
Ok, I see the issue, it's not about Vue. You're simply not using the `filter` option and the images don't have any image extension (.jpg, .png etc).
See:
https://jsfiddle.net/nd5jupe3/1/

**Comment by leonardo-sj** [comment]
Thank you. It solves part of problem.
But the issue persists when the content is generated dynamically.

https://jsfiddle.net/a3pxoLga/1/

**Comment by feimosi** [comment]
That's because you don't give Vue a chance to update the DOM. YOu should remember that the data push to `vueEnv.items` does not get rendered immediately.

https://jsfiddle.net/a3pxoLga/2/

**Comment by leonardo-sj** [comment]
Thank you. It worked.

**Comment by feimosi** [comment]
Great. Then I'm closing the issue.
