### ISSUE TITLE
Does not work when new image is added in the html after calling baguetteBox.run()

### ISSUE THREAD

**Issue by CHANist** [feimosi/baguetteBox.js#159]
I am trying to use the library, and it works great, when I initialize 2 images in the dom, then run the baguetteBox. Then I try to add another new image in the dom, but this time, it doesn't work, even if I call baguetteBox.run() again, after the creation of the new image, inside setTimeInterval().

**Comment by feimosi** [comment]
`baguetteBox` does not work with dynamically added images. It caches the gallery on `run` and works on that data even when re-run. You probably need to invoke `destroy` first and then `run` again,

**Comment by CHANist** [comment]
thanks

**Comment by chris0610** [comment]
Which destroyed method are you referring to? I'm facing the same problem.
