### ISSUE TITLE
Bug in MS Edge

### ISSUE THREAD

**Issue by tallon1252** [feimosi/baguetteBox.js#163]
I think there's a bug with baguetteBox.js and Microsoft Edge.

My code is the following:
```
<div id="wellness-oase-gallery" class="grd-row bathworld-gallery">
  <div class="image">
    <a href="./standards/img/content/badwelten/wellness-oase/wellness-oase-gallery-1-big.jpg"></a>
  </div>
  <div class="image">
    <a href="./standards/img/content/badwelten/wellness-oase/wellness-oase-gallery-2-big.jpg"></a>
  </div>
</div>
```

So i got the images as backgrounds and a absolute positioned link inside the child divs.
When i now click on the link, every browser except Edge opens the lightbox and everything works fine.

Is this lightbox not compatible with Edge, only Internet Explorer? That would be kinda funny…

I'd like to help fixing this bug. :)

**Comment by feimosi** [comment]
That's interesting, are there any error in the console? Could you prepare a jsfiddle with that example?

**Comment by tallon1252** [comment]
While working on on my project, i changed the HTML & CSS structure. Know the lightbox is working great.
I think the bug that i had was not related to baguetteBox… it was more kinda my fault, sorry for that. ✌️

**Comment by feimosi** [comment]
No problem. I'm glad it works now :+1:
