### ISSUE TITLE
How to deal with without jpg | png suffix pictures, like Ali cloud storage of such pictures

### ISSUE THREAD

**Issue by maweiyi** [feimosi/baguetteBox.js#165]
Like this :

 `<a href="http://flytracer.oss-cn-hangzhou.aliyuncs.com/143fbc3c-5343-b599-55d0-0577fbba786e" data-caption="Golden Gate Bridge">
                        <img src="http://flytracer.oss-cn-hangzhou.aliyuncs.com/6962f528-da36-1b81-f016-2b369a4e3eae">               
 </a>`

**Comment by feimosi** [comment]
Hi, it was already answered in #145.

You can write e.g.
```js
baguetteBox.run('.gallery', {
  filter: /.*/i
});
```
