### ISSUE TITLE
Open an image programmatically

### ISSUE THREAD

**Issue by leonardo-sj** [feimosi/baguetteBox.js#166]
Is there a way to open an image programmatically ?
Something like baguetteBox.load(index); ?

**Comment by feimosi** [comment]
Such functionality is not released yet, but you can download the code of this PR: https://github.com/feimosi/baguetteBox.js/pull/155

**Comment by leonardo-sj** [comment]
Thanks. But I couldn't find the method show(index, gallery) on the dev branch.
The return is:
return {
        run: run,
        showNext: showNextImage,
        showPrevious: showPreviousImage,
        destroy: destroyPlugin
    };

**Comment by feimosi** [comment]
As I said you should download the code of the PR. It's on the

**Comment by feimosi** [comment]
Resolved in #166
