### ISSUE TITLE
How to rotate an image ?

### ISSUE THREAD

**Issue by jonny77** [feimosi/baguetteBox.js#168]
First off .Thanks for great tool. 
In my project  some images are up side down , i want to rotate image. but i did not find the  customization options .

**Comment by feimosi** [comment]
Hi @jonny77,

If I understand correctly, the images are upside down on purpose? Can't you just save them properly rotated? That's not baguetteBox responsibility to do so.
You may also want to read about CSS ` transform: rotate()`:
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate

Related: #164

**Comment by jonny77** [comment]
I know what you mean , but users on my site  do not upload the images properly , so i just want to make the baguetteBox to make it possible to rotate images

**Comment by feimosi** [comment]
If you mean a rotation functionality included in the UI (as some buttons) then sorry, it's not possible, you have to implement it yourself.
