### ISSUE TITLE
Loading spinner stays longer than needed!

### ISSUE THREAD

**Issue by cyberiaa** [feimosi/baguetteBox.js#17]
I finally found a great pure Javascript image plugin! Thank you!

It seems loading spinner stays for few more seconds after completion of image. In one case it remained for ever (I use latest FF).

PS:
As a feature request do you think about zoom effect? Something like https://github.com/bmcmahen/image-zoom or Fluidbox

**Comment by feimosi** [comment]
I'm really glad you like my work.

The spinner disappears with the onLoad event. If it stayed forever, it might have been a browser bug. There's nothing to do, that I'm aware of.

The images used are interlaced, so even though it seems the image is loaded, the browser may still be downloading it (take a look at dev tools).

The feature idea seems interesting, but I want to keep the plugin small and simple, so I have to reject it. Anyway thanks.
