### ISSUE TITLE
On Screen Left/Right Nav Arrows Missing in Chrome

### ISSUE THREAD

**Issue by mike-ward** [feimosi/baguetteBox.js#170]
The onscreen left/right arrows are missing in Chrome. The left/right arrow buttons do work.

To repro:

1. Open Chrome and navigate to the bagueeteBox demo site.
2. Open one of the demos

Also fails in Firefox.

Nav arrows appear in IE and Edge.

**Comment by feimosi** [comment]
Sorry, I don't quite understand. Could you explain what you mean? Which onscreen arrows?

**Comment by feimosi** [comment]
Sorry, I don't quite understand. Could you explain what you mean? Which onscreen arrows?

**Comment by mike-ward** [comment]
Sure,

The buttons with the chevrons that appear left and right of the images are missing. 

Chrome:

![image](https://user-images.githubusercontent.com/567927/36029497-64139ca6-0d71-11e8-9f32-fb5b4aa0a868.png)

Edge:

![image](https://user-images.githubusercontent.com/567927/36029529-8c2309fc-0d71-11e8-84e6-76f386e69c85.png)

**Comment by feimosi** [comment]
Alright, I see, do you happen to have a touchscreen laptop?

**Comment by mike-ward** [comment]
Nope, plain old desktop.

**Comment by feimosi** [comment]
That's really strange. I couldn't reproduce it on several machines.

Please try:
- opening the demo page in Incognito mode,
- looking into DevTools for any errors,
- checking on another PC / laptop / OS,
- running the script locally with the `buttons` option set to true.

**Comment by mike-ward** [comment]
Two computers at work show this issue. I'll check the browser console Monday. On my home computer, I see the buttons. The buttons overlay the image. Maybe it's a css issue?

Home computer, Chrome:

![image](https://user-images.githubusercontent.com/567927/36075255-57eceb8a-0f1a-11e8-90ee-f73dc605e3c1.png)

**Comment by feimosi** [comment]
Shouldn't be the CSS. Do you see the button `<svg>` in DevTools -> Elements?

**Comment by mike-ward** [comment]
I checked the consoles of FireFox, Chrome and Opera (all do not show the arrows) and did not see any warnings or other messages. 

I fired up the inspector in Firefox and found a that the style, `display: none` is set on both the previous and next buttons. If I remove the checkbox on `display: none` in the inspector the buttons appear. Screen shot below:

![image](https://user-images.githubusercontent.com/567927/36099853-1ff55010-0fd2-11e8-8a32-a3d6cbac7216.png)

**Comment by feimosi** [comment]
What happens if you run:
`'ontouchstart' in window`
in the console?

**Comment by mike-ward** [comment]
No change.

I was able to get the buttons to appear in Chrome by explicitly setting the option  `buttons: true` in the `run` API.

**Comment by feimosi** [comment]
That's what suspected. If you're 100% sure you don't have a touch-enabled device, then it looks like a software bug. It's out of my reach. You have to use `buttons: true` in such case or implement your own logic wrapping baguetteBox invocation.

Related: #95

**Comment by mike-ward** [comment]
In the Edge browser on the same box: 

`'ontouchstart' in window
false`

**Comment by feimosi** [comment]
That's a very strange case. I don't know whether it's an issue on your machine, browser version or what. If you find a reliable way to detect mobile devices feel free to let me know.
