### ISSUE TITLE
Programmatic run

### ISSUE THREAD

**Issue by mikemix** [feimosi/baguetteBox.js#171]
How to programmatically display the gallery? I would like to pass images by myself instead of specifying the selector to the `run` method.

**Comment by feimosi** [comment]
Sorry, the core mechanism is based on selectors. Alternatively you can create the `<a>` tags and hide them with `display: none`.

**Comment by mikemix** [comment]
Pity, I have an inifite photo slider built with amazing [slick.js](http://kenwheeler.github.io/slick/). To make it appear as if infinite it repeats the links multiple times. I have only 2 images for instance, but in DOM there are 4, so Baguette displays 4 images.

Shame that initialization part is not abstract enough.

**Comment by feimosi** [comment]
You can try with the `filter` option and some text appended to the href like `?duplicate`. That's just an idea.

**Comment by mikemix** [comment]
That's not going to work, I have to use another script.
