### ISSUE TITLE
Baguette Box not working with AmazonS3 URL when there is no file extension

### ISSUE THREAD

**Issue by DiegoCotini** [feimosi/baguetteBox.js#175]
I started using AmazonS3 to store files and images and I noticed that Baguette Box stopped working because the AmazonS3 image URL didn't contain the file extension (like .jpg), only the file key.

I guess Baguette Box doesn't recognize it as a image automatically because of the missing image extension and when I click on the link the image is being opened in the way without using Baguette Box. 

I'm just using the code below to call Baguette Box:

baguetteBox.run('#PhotoContainer');

URL example: https://mybucket-com.s3.amazonaws.com/1bf8e7a2-a7ca-49ca-ab52-086ead4aa46e

I've tried to figure some solution out on the web and I've opened a question on stackoverflow trying to check if there is a way to make it work. I've taken a look inside the code but I haven't found anything that helped me.

https://stackoverflow.com/questions/49032844/baguette-box-not-working-with-amazons3-url-when-there-is-no-file-extension

If there isn't any way to make it work or it may some kind of option be done to allow it in the future?

Thanks

**Comment by feimosi** [comment]
Hi, that's already been solved in #145.

**Comment by DiegoCotini** [comment]
Hi @feimosi, that solution worked. Thank you!
