### ISSUE TITLE
Use style attribute in package.json

### ISSUE THREAD

**Issue by jonty-comp** [feimosi/baguetteBox.js#176]
Hi, great library!

My build toolchain uses postcss-import and cssnext instead of Sass and uses the `style` attribute in `package.json` to find the compiled file for bundling and minifying into my project.

Could you possibly add the `style` attribute as follows?:

```json
    "style": "dist/baguetteBox.css"
```

This way, I and other users of postcss-import can use 
```css
@import 'baguetteBox.js'
```
in our css files instead of 
```css
@import '../../../node_modules/baguetteBox.js/dist/baguetteBox.css';
```

Many thanks!

**Comment by feimosi** [comment]
Hi, that's a cool idea, thanks for reporting!

**Comment by feimosi** [comment]
You have to wait for the next release or you can install from the `dev` branch. In any case let me know if it works fine now :slightly_smiling_face:

**Comment by jonty-comp** [comment]
Hi, works great thanks!
I'm developing a project that won't be out for quite a while so i'm sure you will have published a version by the time I need it.  Until then I'll use `dev`! 👍

**Comment by delphilord** [comment]
Thanks for This Great work.
I have a Problem with it. I use this awesome library in a site, That I must show hit of every picture.
I coded a Handler that increases counter of every Image in SQL database and then reads and returns picture as response and uses**async: False** to do not get a hit on the counter for all images when a page with many images is opened

But left and the right pictures also is hit when the bauggetbox overlay is opened.
How can I handle This situation?
