### ISSUE TITLE
Resize image on the fly problem

### ISSUE THREAD

**Issue by BorisZyryanov** [feimosi/baguetteBox.js#177]
Hello!
I like your lightbox very much, but I have some problems with it.
Lightbox don't get any image, when the image's link looks like http://path/img.php?id='1234125'.
I tried to use a filter option (`{filter: '/.+\\.(gif|jpe?g|png|webp|php)/i'}` and `{filter: '/.+\\.(gif|jpe?g|png|webp|php\?id)/i'}`), but that didn't work.
Nevertheless the link is working and I get an image in the browser.
Could you make it clear for me, please.

**Comment by feimosi** [comment]
Hello!
Looks like you have one extra slash in the regex, should be:
`/.+\.(gif|jpe?g|png|webp|php)/i`

It works for me like that.

```js
/.+\.(gif|jpe?g|png|webp|php)/i.test("http://path/img.php?id='1234125'")
// > true
```

**Comment by BorisZyryanov** [comment]
Hello!  
Thank you very much for your advice!  
I'm a glad that you have found a mistake in the regex in my code.  
The IDE made a double slash, when I pasted a regex from README.md.
