### ISSUE TITLE
m.test is not a function when using filter

### ISSUE THREAD

**Issue by sebastian-raubach** [feimosi/baguetteBox.js#178]
I'm using the filter setting suggested in #145 because the URLs I use don't have the usual image extensions.

If I use this filter though, I get the following error:

    vue.esm.js?efeb:1717 TypeError: m.test is not a function
        at eval (baguetteBox.min.js?a8fa:7)
        at HTMLCollection.filter (<anonymous>)
        at eval (baguetteBox.min.js?a8fa:7)
        at NodeList.forEach (<anonymous>)
        at Object.run (baguetteBox.min.js?a8fa:7)

This is the code I use:

    baguetteBox.run('div.owl-item', {
        'captions': 'true',
        'filter': '/.*/i'
     })

And an example of the HTML

    <div class="owl-item active" style="width: 413.993px;">
        <a href="http://localhost:8080/buntata/v1.1/media/23" class="image owl-item">
            <div style="background-image: url(&quot;http://localhost:8080/buntata/v1.1/media/23?small=true&quot;);"></div>
        </a>
    </div>

When I remove the filter, I don't get the error, but baguettebox doesn't show up.

Any ideas?

**Comment by feimosi** [comment]
Hi, actually the filter property should be a Regex, not a string. Try it with:
`'filter': /.*/i`

**Comment by sebastian-raubach** [comment]
Ah, yes. That makes sense. Sorry about that. I'm a step closer to getting it to work now :)

**Comment by feimosi** [comment]
Great :)
