### ISSUE TITLE
Custom image filter

### ISSUE THREAD

**Issue by rhrn** [feimosi/baguetteBox.js#18]
Hello @feimosi they nice lib)

I was interested then trying use with image placeholder services, where gallery builded unexpectedly.
So after debug i find image filter that works by regex rule `/.+\.(gif|jpe?g|png|webp)/i`

May be add custom filter?

```js
baguetteBox.run('.gallery', {
  filter: new RegExp('.+\.(gif|jpe?g|png|webp)', 'i')
});
```
and to skip filtering
```js
baguetteBox.run('.gallery', {
  filter: null
});
```

**Comment by feimosi** [comment]
This should help. Sorry it took me so long, but I was busy
