### ISSUE TITLE
Prev/Next/Close buttons showing at bottom of page

### ISSUE THREAD

**Issue by marcanuy** [feimosi/baguetteBox.js#182]
Hi, I am using baguetteBox.js in a website in two different pages:
- homepage
- gallery

In the gallery it works well but in the homepage I can't find why the lightbox controls are appearing at the bottom of the webpage like this:

![screenshot](https://i.imgur.com/gJtzQk2.png)

In both webpages, I am loading the same assets, and console does not show any errors.

You can see it live at:
- homepage: http://keraban.marcanuy.com <- the one with the problem
- gallery: http://keraban.marcanuy.com/gallery/

Using _baguettebox.js/1.10.0 (with Bootstrap 4 too)

Any idea how to fix it?

X-post: [Stackoverflow](https://stackoverflow.com/q/50511436/1165509).

**Comment by marcanuy** [comment]
Well they weren't loading the same assets, adding the style sheet fixes it `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css" />`.

**Comment by feimosi** [comment]
Hey, sorry for the late reply. I'm glad you resolved the issue :+1:
