### ISSUE TITLE
Feature Request: infinity gallery

### ISSUE THREAD

**Issue by ppi-buck** [feimosi/baguetteBox.js#184]
Cheers and first of all **thank you** for this amazing tool!

Is there a reason why you don't provide an option to make the gallery start over again after the last one was reached? 
If not I'd like to propose this as a feature request for [v2.0](https://github.com/feimosi/baguetteBox.js/milestone/1) ;-) 

Most other galleries do have an option to turn it on/off based on the default state.

Thanks in advance

**Comment by feimosi** [comment]
Infinity gallery will be available with   https://github.com/feimosi/baguetteBox.js/pull/207
