### ISSUE TITLE
counting image hit , Need some guide

### ISSUE THREAD

**Issue by delphilord** [feimosi/baguetteBox.js#187]
Thanks for This Great work.
I have a Problem with it. I use this awesome library in a site, That I must show hit of every picture.
I coded a Handler that increases counter of every Image in SQL database and then reads and returns picture as response and uses **async: False** to do not get a hit on the counter for all images when a page with many images is opened
for example /photohandler.ashx?id=67.jpg

But left and the right pictures also is hit when the bauggetbox overlay is opened.
How can I handle This situation?
I am not JS expert, can I modify Functions (which function or functions?) to send extra query string only for the currently visible image to make counter increase routine run only when this Query String is sent?
for example /photohandler.ashx?id=67.jpg&Hit=1

**Comment by feimosi** [comment]
I presume the issue has been fixed.
