### ISSUE TITLE
Doesn't work in AngularJS ng-repeat directive

### ISSUE THREAD

**Issue by Bradmartin0905** [feimosi/baguetteBox.js#19]
The following works, copied from the build folder (of course changed the path on an image for local testing).

However when I call the same class 'baguetteBoxOne' on an anchor/image inside ng-repeat it doesn't work. Any work around? I'm a novice at JS so I don't know if I will be able to assist very much on the issue.

     <div class="baguetteBoxOne gallery">
                        <a href="img/1-1.jpg" data-caption="Golden Gate Bridge"><img src="img/thumbs/1-1.jpg"></a>
                        <a href="img/1-2.jpg" title="Midnight City"><img src="img/thumbs/1-2.jpg"></a>
                        <a href="../images/SouthernRebels Logo.jpg"><img src="../images/SouthernRebelsLogo75px.jpg"></a>
                        <a href="img/1-4.jpg"><img src="img/thumbs/1-4.jpg"></a>
                        <a href="img/1-5.jpg"><img src="img/thumbs/1-5.jpg"></a>
                        <a href="img/1-6.jpg"><img src="img/thumbs/1-6.jpg"></a>
                        <a href="img/1-7.jpg"><img src="img/thumbs/1-7.jpg"></a>
                        <a href="img/1-8.jpg"><img src="img/thumbs/1-8.jpg"></a>
                    </div>

The next snippet is the code in the repeater:

      <tr ng-repeat="u in Users" ng-style="{'color': (u.Status == false ? 'red' : '')}">
                                <td class="baguetteBoxOne">
                                    
                                    <a class="single-popup" href="{{u.ImagePath}}" title="{{u.Username}}'s Profile Pic">
                                        <img ng-src="{{u.ImagePath}}" width="50" height="50" />
                                    </a>
                                </td>

**Comment by Bradmartin0905** [comment]
I've tried moving the class declaration to different parent elements and directly on the anchor and image elements but no advances yet.

**Comment by feimosi** [comment]
Hi, actually, I haven't used Angular yet, so I can't really debug it or check what's wrong.
Make sure the generated code is valid (e.g. src) and take a look at the console if there are any errors.

**Comment by Bradmartin0905** [comment]
No errors. I think its the way Angular generates the elements. I dont have
time to dive deeper right now but Ive seen the same issue on other
"lightbox" type plugins. Thanks.

**Comment by psmolinsky** [comment]
Angular executes directives (calls compile and link functions) downward DOM tree. That's why your `baguetteBoxOne` (put on parent element) always gets executed before `ngRepeat` (put on child element) which means that baguetteBoxOne doesn't find any `<a>` elements because they have not been rendered by `ngRepeat` yet.

Quick fix would be to use `$timeout` service to active baguetteBox after all directives are processed:

    angular.module('myApp')
        .directive('baguetteBoxOne', ['$timeout', function ($timeout) {
            return {
                restrict: 'AC',
                link: function ($scope, $elm) {
                    $timeout(function () {
                        baguetteBox.run('.baguetteBoxOne');
                    });
                }
            };
        });
