### ISSUE TITLE
no previous and next in Luakit Browser

### ISSUE THREAD

**Issue by haheute** [feimosi/baguetteBox.js#199]
With the Luakit Web Browser (version c5328c22), I don't see the previous and next buttons. The close button is visible and works. 

The buttons "Previous" and "Next" are set to `display:none` and the keyboard commands don't work, too. (prev, next, esc). When I remove the `display:none`-style manually, the button appears and works when clicked.

I don't know why this happens. I am on a PC without touch - only mouse and keyboard.

**Comment by feimosi** [comment]
The most common reason for this issue is that your browser is being incorrectly detected as a touch-enabled device. Please try running the script with the following option:

```js
baguetteBox.run('.gallery', { buttons: true });
```

**Comment by haheute** [comment]
okay, thanks.
