### ISSUE TITLE
Responsive images never fall back to default href

### ISSUE THREAD

**Issue by psmolinsky** [feimosi/baguetteBox.js#20]
Responsive images never fall back to default `href`. Image with the biggest size specified by `data-at` attribute is used instead.

I think the problem is on lines 356-360:

	// Find the first image bigger than or equal to the current width
	var i = 0;
	while(i < keys.length - 1 && keys[i] < width)
	    i++;
	result = srcs[keys[i]] || result;

While loop stop before checking the last key (`i < keys.length - 1`) thus there is always some result taken from `srcs` object. I suggest changing the condition to `i < keys.length`. Then `i` will overflow array size, `undefined` will be returned from `srcs` and result will be taken from fallback.

**Comment by feimosi** [comment]
Hi, sorry, but I don't quite understand what you mean. 
It's made on purpose not to overflow the array in case the resolution is bigger than any `data-at` attribute. When there aren't any such attributes, `result` is equal to `href`.
When should it fall back?

**Comment by psmolinsky** [comment]
Of course that in case of no `data-at` attribute, `href` is used. But from [readme](https://github.com/feimosi/baguetteBox.js#responsive-images) I understood that `href` should be also used if screen width is greater than the greatest `data-at` value. I think it makes sense to use it this way, because you usually have few thumbnails with predefined sizes plus original with any size. That's why it should overflow and fall back. What do you think?

**Comment by feimosi** [comment]
No, actually I meant to fall back in case dataset is not supported by the browser. I was thinking in such way that href contains the most casual resolution, let's say 1366x768 and responsive versions are prepared for e.g. mobile, desktop and HiDPI display. In this case for some 4K / 8K screens we need the biggest image possible.

**Comment by psmolinsky** [comment]
Ok. So if you are using `data-at` attributes, `href` is currently useless. Where should the biggest image go if you like to use it for 4K / 8K? I would prefer it in `href` as far as `data-at` values are evaluated as upper limits. Please give me an example.

**Comment by feimosi** [comment]
Yes, exactly. `href` is for the fall back mode, when using `data-set`. if you want to prepare images for 4K resolution you should use `data-at-` with appropriate maximum width. Once again, when designing this, I was thinking about backward compatibility for old IE or old mobiles, which for sure doesn't need the biggest image. In this case it's indeed the upper-limit, unless we run out of possible options - then we take the biggest one available.

**Comment by psmolinsky** [comment]
Sry for delayed answer. Now I understand and it's good enough for me. Then please also write to readme/docs that last `data-at-X` image is used also in case of screen larger then `X`. Thank you.

**Comment by feimosi** [comment]
OK, done.
