### ISSUE TITLE
Error : gallery is undefined 

### ISSUE THREAD

**Issue by thomas573609** [feimosi/baguetteBox.js#201]
Hello, 
I have a issue with baguettebox. Maybe you can help me to fix it.

I used baguette box in 2 div named blockOne and blockTwo

In the first blockOne the lightbox work perfectly, but the blockTwo it doesn't work at all.. 
Into the 2 block I have some lightbox named like this : lightboxEscal, lightboxFenster, lightboxRemb, lightboxPark but they have different name in each div ( blockOne lightboxEscal, blockTwo lightboxEscalTwo) 

Here is how i call baguettebox
> baguetteBox.run('.lightboxEscal',{ buttons:'boolean',});
				baguetteBox.run('.lightboxFenster',{ buttons:'boolean',});
				baguetteBox.run('.lightboxRemb',{ buttons:'boolean',});
				baguetteBox.run('.lightboxPark',{ buttons:'boolean',});

I can click on image, the lightbox work but when I click on the right button ( to see other image ) : nothing and mozilla console return this : 

>  TypeError: gallery is undefined
show  https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.11.0/baguetteBox.js:632:13
showNextImage https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.11.0/baguetteBox.js:601:16
nextButtonClickHandler https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.11.0/baguetteBox.js:87:9

Could you help me to fix this ? 

Best regard.

**Comment by delrueba** [comment]
Not sure if this will fix your issue, but I see three problems
* your options object is wrong, there's a stray comma in each one
* buttons is of type boolean, the value should be true | false. ('boolean' is truthy so i'd imagine it still works though).
* you're sample code tries to initiate the lightboxes from blockOne, you say your error is in block two.
