### ISSUE TITLE
Minor issue on Chrome 56+: "Unable to preventDefault inside passive event listener invocation."

### ISSUE THREAD

**Issue by w-biggs** [feimosi/baguetteBox.js#202]
This is a very minor issue, but I figured it was best to call it to your attention.

On Chrome 56+, touch events cause an error: `Unable to preventDefault inside passive event listener invocation. touchmoveHandler @ baguetteBox.js:107`. This is apparently due to a change the Chrome developers made where `touchstart` and `touchmove` events on the `window`, `document`, or `body` elements are now passive by default.

I haven't noticed any functionality problems, but it does cause the console to spit out a bunch of errors whenever you swipe. This can apparently be fixed pretty easily by using the `touch-action: none` CSS style instead.

Just a heads up!

**Comment by tillkruss** [comment]
Any update on this?

**Comment by feimosi** [comment]
Fixed in v1.11.1
