### ISSUE TITLE
if a video work that prices would not be this script!

### ISSUE THREAD

**Issue by darknefrit** [feimosi/baguetteBox.js#21]
if a video work that prices would not be this script!

**Comment by feimosi** [comment]
I don't understand. What do you mean?

**Comment by iliman** [comment]
I think, he want to support <video> tag in slides.

**Comment by iliman** [comment]
I think, he want to support `<video>` tag in slides.

**Comment by feimosi** [comment]
Then sorry, that's not feasible. The script is built up around the `img` tag, so it'd need too many changes.
