### ISSUE TITLE
Disable body scrolling when swiping images on mobile

### ISSUE THREAD

**Issue by tonimichel** [feimosi/baguetteBox.js#211]
Whenever swiping images on a mobile device, the body scrolls. 
It would be great if the body scrolling behaviour could be disabled – especially for iOS devices.

**Comment by aloysiu3** [comment]
I would appreciate this feature as well. Disable vertical scrolling as long as the gallery is shown.

'noScrollbars' option disables scrolling on desktop, but breaks scrolling on mobile devices. Once the gallery is opened and closed again, the scrolling behavior changes (tested on iOS safari, chrome, ff).

**Comment by ketonik** [comment]
Ah yes, wondering if there was a solution to disable body scrolls. It's so easy to accidentally swipe on an angle on iOS, the body scrolls and swiping stops working.

**Comment by ketonik** [comment]
This swiping body movement makes image navigation very difficult on iPad. I wonder if it is possible then to tap on each half of image left side right side to navigate? Imaginary vertical line down centre of image determines left / right
left half of image image back <
right half of image go forward >

**Comment by feimosi** [comment]
Unfortunately, I don't have access to any iOS device and I'm really busy nowadays. If anyone wants to give it a try, pull requests are welcome.

**Comment by feimosi** [comment]
Please let me know if the issue still exists on v1.11.1

**Comment by aloysiu3** [comment]
I just implemented the latest version and its working perfectly. No more vertical scrolling while swing through the gallery. (Tested on iPhone 7, iOS 13, latest Safari, Chrome and Firefox)

**Comment by feimosi** [comment]
Great, thanks!
