### ISSUE TITLE
Update docs for clarity

### ISSUE THREAD

**Issue by rickibarnes** [feimosi/baguetteBox.js#214]
https://github.com/feimosi/baguetteBox.js/issues/156

As per this issue, beginners or people who aren't that sharp on JS are stumbling on that step.

Why not update the Usage to say "Initialize the script when the DOM is ready, e.g."
`<script>
window.addEventListener('load', function() {
  baguetteBox.run('.gallery');
});
</script>`

I bring this up because I teach for a web development bootcamp. Our students are excellent, but they're taking in a flood of information, and this kind specificity in docs is really helpful to them to cement the principles that they are learning.

**Comment by DaKid74** [comment]
Exactly the same problem I had, thanks, and yes please update documentation ;-)

**Comment by feimosi** [comment]
Sure, I'll add it :slightly_smiling_face:
