### ISSUE TITLE
Is there a way to trigger the logic for choosing images based on resolution on resize

### ISSUE THREAD

**Issue by Hlsgs** [feimosi/baguetteBox.js#217]
Right not I'm reainitialising baguetteBox. Btw, is there a point in destroying it first, of just recalling `run` is fine?

**Comment by feimosi** [comment]
Yes, you should `destroy` it first to remove all event handlers and free the memory.

**Comment by feimosi** [comment]
Closing

**Comment by Hlsgs** [comment]
@feimosi The main question was in the title...

**Comment by feimosi** [comment]
That's not possible, image size is chosen when you run the gallery.

**Comment by Hlsgs** [comment]
Cool, thanks for the answer!
