### ISSUE TITLE
Clicking image too quickly opens image URL instead of gallery

### ISSUE THREAD

**Issue by PhygrianPhrog** [feimosi/baguetteBox.js#218]
I thought I could get round it with the images fading-in, forcing the user to wait long enough for the gallery to load, but even 1.5sec fade-in is not enough: https://rosiewhitepainting.com/index.html

Am I doing something wrong? Here's the HTML https://github.com/rosiewhitepainting/website/blob/master/index.html

Thanks for providing the gallery, and any assistance for the above issue. Also, where do I attribute you? In the footer or in HTML comments?

**Comment by PhygrianPhrog** [comment]
Ok, I figured it out.

Baguettebox was failing to load _some of the time_, because it was set to load asyncronously and as a result it sometimes loaded after the init script had been executed at the bottom of <body>. 

My solution was to wrap the init script in window.addEventListener('load', function() { ... } which waits for the whole window and any scripts etc to be ready before executing.

**Comment by balibebas** [comment]
https://habd.as/post/managing-async-dependencies-javascript/
