### ISSUE TITLE
Carousel option

### ISSUE THREAD

**Issue by cybernauta** [feimosi/baguetteBox.js#22]
Very interesting project. It could be useful to add a "carousel" option to cycle from the last image to the first (or from the first to the last image). Obviously the last or first image "bounce effect" should be disabled when the carousel option is active. Thank you

**Comment by feimosi** [comment]
Hi, thanks for the suggestion. I've already considered such a case and prepared two public methods to make it easier to implement. With `showNext` and `showPrevious` (described in the readme) you can create your own presentation / carousel effect. I didn't make it as a part of the plugin to keep it minimalistic and relatively small in size.
Cheers.

**Comment by cybernauta** [comment]
Thank you for quick reply. I'm not a real JS programmer so do you have an example of showNext and showPrevious to jump from/to the first/last image in a carousel way?

**Comment by feimosi** [comment]
I thought you want to alternate the direction, so from the first to the last one and from the last to the first one. Right now it's not possible to switch to certain index in the gallery. Also if you want to avoid 'bounce effect' you'd have to take the number of images and keep attention how far you can loop.
Something like this:
```js
function carouselRight(i, size) {
	if(i >= size - 1) {
		carouselLeft(0, size);
	} else {
		baguetteBox.showNext();
		setTimeout(function() {
			carouselRight(++i, size);
		}, 1000);
	}
}

function carouselLeft(i, size) {
	if(i >= size - 1) {
		carouselRight(0, size);
		return;
	} else {
		baguetteBox.showPrevious();
		setTimeout(function() {
			carouselLeft(++i, size);
		}, 1000);
	}
}

var size; // assign the number of the images
carouselRight(0, size);
```
That's not the perfect code, but does the job. Is such a solution sufficient for you?

**Comment by cybernauta** [comment]
Ok, that's an useful solution.
Thank you!

**Comment by feimosi** [comment]
You're welcome
