### ISSUE TITLE
Add custom class to img tag

### ISSUE THREAD

**Issue by sebastian-raubach** [feimosi/baguetteBox.js#230]
I'm trying to fix an issue where images that are showing in baguetteBox are showing up rotated instead of the right way up.
I found a JS library called exif-js that can be used to determine the orientation and I'd like to be able to add a class to the `img` tag within baguetteBox to be able to rotate it based on the exif information using a CSS transform.

Is this possible at all? Is there a way to get the current image during the `onChange` event?

**Comment by stefansl** [comment]
You should fix your images while uploading - not in the frontend. That would be another performance issue

**Comment by sebastian-raubach** [comment]
Unfortunately, I don't have any control over the images themselves.
However, I'm sure there are plenty of other use cases where adding a class to the image tag would be of use.

**Comment by feimosi** [comment]
Could you provide an example showing how this should be used? As an extra `data-` attribute per each img or how?

**Comment by sebastian-raubach** [comment]
Ideally providing a function as part of the `userOptions`. Something like this:

```
baguetteBox.run('.gallery', {
  imgClass: (img, index) => {
    // For my use-case, I would read the EXIF data here based on the img
    return `test-${index}`
  } 
})
```

Where currently, I do this:
```
baguetteBox.run('.image-grid', {
  afterShow: () => {
    const overlays = document.querySelectorAll('#baguetteBox-overlay img')

    overlays.forEach(n => {
      if (n.complete && n.naturalHeight !== 0) {
        // Rotate the image on load based on EXIF information
        this.rotateBasedOnExif(n)
      } else {
        n.addEventListener('load', () => {
          // Rotate the image on load based on EXIF information
          this.rotateBasedOnExif(n)
        })
      }
    })
  }
})
```

**Comment by feimosi** [comment]
Sorry, that's out of the scope of this project. We can just considering adding a `data-` attribute to set the image class. That gives you the same result.

**Comment by sebastian-raubach** [comment]
It wouldn't really give me the same result, as I'd read the exif from the loaded image. If I need to provide the class in a `data-` attribute, I'd have to read the image separately first.
It's ok though, my solution works. Just thought it might be something that other people see as a valid use-case as well.

**Comment by feimosi** [comment]
Oh I see, understood. I'm glad there is still a workaround. 
Closing then.
