### ISSUE TITLE
baguetteBox as a WordPress Plugin for the Block Editor Gallery Block

### ISSUE THREAD

**Issue by goaround** [feimosi/baguetteBox.js#231]
Hi @feimosi,

I use baguetteBox.js to add a lightbox to the WordPress Block Editor Gallery Block. I would like to release my little plugin with baguetteBox.js to the WordPress Plugin Repository. It would be under the GPL-2.0 and for free of course.

https://github.com/goaround/gallery-block-lightbox

I know, baguetteBox is MIT but I still would like to know if you are okay with it?

**Comment by feimosi** [comment]
Hi @goaround,

Of course, as long as your plugin is open source and free, you can use baguetteBox.js there :slightly_smiling_face:

**Comment by goaround** [comment]
Thank you!

**Comment by goaround** [comment]
Its now live: https://wordpress.org/plugins/gallery-block-lightbox/
