### ISSUE TITLE
No way to destroy

### ISSUE THREAD

**Issue by louy** [feimosi/baguetteBox.js#26]
Unfortunately this makes the plugin useless for me, even though it is very nice. I needed to use it as a component in a single-page app.

**Comment by feimosi** [comment]
Hi, does #24 fix your problem? Actually the event listeners are the main problem in SPA I guess.

**Comment by louy** [comment]
Hi @feimosi,
It's just a partial solution. We need a method to destroy the plugin, removing all event handlers etc. This would include both keyboard keys and click handlers. But I agree with #24 as well.

Typically, using `jQuery.off` would be enough. But if the overlay is visible, it should be removed as well.

**Comment by feimosi** [comment]
Okay, you're right. I'll take care of that soon.

**Comment by feimosi** [comment]
Could you please check if it works like it should before I make the next release? I hope I haven't forgotten about any handler to unbind.

**Comment by louy** [comment]
Seems good. Thanks! 👍
