### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by anabreu** [feimosi/baguetteBox.js#32]
Hi there,
I apologise if this is a dumb question, I am no coder...
How could I use the baguetteBox in such a way that a gallery would be triggered by a single image?...
I have tried adding the href code on the first image, and afterwards insert the code only for the following images, but this gets faulty results, sometimes it works, sometime it doesn't... :)
(I tried this solution, because it actually works with another script I used in the past)
Any hint would be greatly appreciated...
Thank you so much,
Ana
![bagettebox-single-image](https://cloud.githubusercontent.com/assets/13575204/8989555/be4d9b06-36e4-11e5-95e5-a90c9d3aeb59.jpg)

**Comment by anabreu** [comment]
...I should have said that this actually works on a desktop browser, but the faulty results happens on a mobile website I'm trying to put together...

**Comment by anabreu** [comment]
...I've uploaded my file to http://m.coresaocubo.pt/05-portfolio-teste-3.html (please remember I am not a coder, and adding to that, I'm from the tables/dinossaur era... please play nice ^_^ ).

**Comment by feimosi** [comment]
Hi, first of all to clarify, what you want to achieve is to trigger the
gallery only when clicking on a particular image? This is not how the
script was built, be default it binds event handlers to every image. Also
the link you've provided doesn't work.
To solve your issue you can make a workaround and insert HTML code of your
gallery twice , where one is not displayed.

**Comment by feimosi** [comment]
No response, assumed as resolved.
