### ISSUE TITLE
No text wrap for long caption 

### ISSUE THREAD

**Issue by ste83** [feimosi/baguetteBox.js#36]
Hi,
is it possible to force text wrapping of the captions?
When the text is too long or when the window is too small the caption simply goes out of view because it stays as a single line.
I have tried playing with the css file, in particular with the #baguetteBox-overlay .full-image figcaption {} but couldn't find a solution by myself...any help?
Thanks,

Stefano

**Comment by feimosi** [comment]
I hope that helps. Could you test it before I make a patch release? Just in case.

**Comment by ste83** [comment]
It works perfectly! Thanks a lot! =)
