### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ohuio** [feimosi/baguetteBox.js#39]
line 160 
imagedEventHandlers[imageElement] = imageElementClickHandler;

when there has two or more  img element is the same then can not unbind it because the imageElementClickHandler is not the same

can change it to
imagedEventHandlers[galleryID+'__'+imageIndex] = imageElementClickHandler;
?

**Comment by feimosi** [comment]
Hi, finally I've found some time to look at it. Indeed you were right. The code was prone to memory leaks and undefined behavior if more than one image had the same href. Now the hash is more unique and it should work as long as there won't be multiple same images in one gallery (may be improved in the future). 
Thanks for reporting that!
