### ISSUE TITLE
Add support for showing image(s) without predefined HTML structure

### ISSUE THREAD

**Issue by webpepper** [feimosi/baguetteBox.js#42]
It looks like there's currently no way to show images programmatically.

I.e., the following is not possible, as far as I can tell.
```javascript
baguetteBox.run('myimage.jpg');
```
or

```javascript
baguetteBox.showImage({src:'myimage.jpg', caption: 'whatever'});
```

Having this ability would allow for easier integration with other scripts and custom markup.

I managed to bastardize a new "showImage" function for myself out of what's available, but such a simple addition could make this script a lot more useful to other people too, I think.

**Comment by feimosi** [comment]
Hi, thanks for your suggestion, but this could be achieved by manually creating the gallery elements, appending them hidden to the document and firing the click event. What do you think?
I want to keep the gallery as lightweight as possible.

**Comment by feimosi** [comment]
I'm closing the issue after deciding it'd need too much code overload.
