### ISSUE TITLE
Click an image / swipe up to close the lightbox

### ISSUE THREAD

**Issue by matejperko** [feimosi/baguetteBox.js#43]
Hi!

Is it possible to add an option, to be able to close the lightbox if you click the open image or maybe if you swipe up, like it is popular now with mobile apps?

Regards,
Matej

**Comment by feimosi** [comment]
Hi,
I like the idea of swipe up event. Maybe I'll manage to implement it in the next release.

Regards,
Marek

**Comment by feimosi** [comment]
Please let me know if that solution works fine for you.

**Comment by matejperko** [comment]
Works a treat! Thank you! 

I might have another suggestion. Is it possible to animate the swipe, so the photo moves with the swipe upwards and then disappears?

**Comment by feimosi** [comment]
Of course it's possible, but it'd require much more new code. Maybe in the future releases :)
