### ISSUE TITLE
When the picture isn't loaded completely, keep the picture invisible ?

### ISSUE THREAD

**Issue by zzstrwolf** [feimosi/baguetteBox.js#44]
is there any options make that when the picture isn't loaded completely, keep the picture invisible (just loading effect)?
Thank you very much. The Script is simple and nice !

**Comment by feimosi** [comment]
Hi!
There isn't such option, sorry. But I think you'd like to read about [interlaced images](http://blog.codinghorror.com/progressive-image-rendering/)
With that, there's no need to hide images, and a proper UX is preserved.

**Comment by zzstrwolf** [comment]
Thanks.
I have added image.style.display = 'none' when image.onload change the attribute visible.

**Comment by feimosi** [comment]
Okay, then I can close the issue.
