### ISSUE TITLE
Added 4 new features

### ISSUE THREAD

**Issue by H-Lo** [feimosi/baguetteBox.js#45]
Hello!

I have 4 new features to your code:

-- <em>titleTag</em> - copy title tag from thumbnail to main image; this one is good for copyright notice, but to have fullscreen photos

-- <em>removeButtonsAfter</em> - remove navigation and close buttons after some idle time and show them on mousemove; this one is very good when using keyborad navigation

-- <em>noScrollbars</em> - remove scrollbars from body element while displaying image in overlay

-- <em>fullScreen</em> - display overlay in full screen

All features are disabled by default and can be set using options object while calling run().

Modified file is available here: http://malizwrk.net/baguetteBox-v1.4.2/baguetteBox-H.Lo.js
Live demo is available here: http://malizwrk.net/gallery/

Tried to write code in your style.

**Comment by feimosi** [comment]
Hello @H-Lo
Thanks for your contribution to the project! I need to first review each feature myself, but as I'm busy these days, it may take time. Anyway I can agree with each one, these are really good ideas :)
Would you mind creating a pull request for each feature? That would be the best approach and allow  easier code comparison.

Best regards,
Marek

**Comment by H-Lo** [comment]
Hello!

Of course you have to review :)
Today is my second day on github, I registered just because of your product.
First I have to check what does pull request mean :)

Best regards,
Hrvoje

**Comment by H-Lo** [comment]
Created 5 pull requests - one for every feature and one with all features merged in one file.
Best regards,
Hrvoje

**Comment by feimosi** [comment]
Thanks once again. When only I find time I'll go through each one.
Best regards,
Marek

**Comment by H-Lo** [comment]
Thank you for the great plugin. Those are just small enhancements :)
Best regards,
Hrvoje

**Comment by feimosi** [comment]
I've accidently closed all open issues when doing a force push (actually it was GitHub). Could you reopen them? I mean those for each suggested feature.

**Comment by feimosi** [comment]
Actually, you can leave them closed. I can manage to merge the changes anyway and give the current status here.

**Comment by feimosi** [comment]
A few questions regarding _removeButtonsAfter_ feature:
1. Is there any reason behind _navigationVisible_ variable, beside minor performance gain ?
2. Why do you reset the timeout for every image change? I don't find it necessary for UX.

**Comment by feimosi** [comment]
Resoled by #46, #50, #52, #54 and included in v.1.5.0.
Feature #49 (_removeButtonsAfter _) will be integrated in some future release, as it interferes with too much logic.

**Comment by H-Lo** [comment]
1) The variable is here because of performance, and if I remember well - there was some unwanted flicker
2) If you do not clear timeout when hiding an overlay, it will trigger "hide buttons"; when opening overlay again, it opens without buttons until mouse moved
------
This feature need a lots of code, so it not necessary for me to put it in your code.
I downloaded 1.5.0 and added this features for my personal use.
You can see it here in action: http://malizwrk.net/gallery/job/
Thanks for accepting other features!

**Comment by H-Lo** [comment]
1 - The variable is here because of performance, and if I remember well - there was some unwanted flicker
2 - If you do not clear timeout when hiding an overlay, it will trigger "hide buttons"; when opening overlay again, it opens without buttons until mouse moved
------
This feature need a lots of code, so it not necessary for me to put it in your code.
I downloaded 1.5.0 and added this features for my personal use.
You can see it here in action: http://malizwrk.net/gallery/job/
Thanks for accepting other features!

**Comment by H-Lo** [comment]
1 - The variable is here because of performance, and if I remember well - there was some unwanted flicker
2 - If you do not clear timeout when hiding an overlay, it will trigger "hide buttons"; when opening overlay again, it opens without buttons until mouse moved
------
This feature need a lots of code, so it not necessary for me to put it in your code.
I downloaded 1.5.0 and added this features for my personal use.
You can see it here in action: http://malizwrk.net/gallery/job/
Thanks for accepting other features!

**Comment by H-Lo** [comment]
1) The variable is here because of performance, and if I remember well - there was some unwanted flicker
2) If you do not clear timeout when hiding an overlay, it will trigger "hide buttons"; when opening overlay again, it opens without buttons until mouse moved

This feature needs a lots of code, so I don't wanna force you to include it if you don't want.
Today I downloaded version 1.5.0 and added this feature for my personal use.
You can see it here in action: http://malizwrk.net/gallery/job/

Many thanks for accepting other features!

**Comment by feimosi** [comment]
Ok, now it's more or less clear. 
In the near future I'm going to focus on release 2.0 with refactored code and dropped support for < IE11, so maybe then it'll fit well.
In case you find any bugs don't hesitate to open a new issue :)
