### ISSUE TITLE
npm is still on 1.3.2

### ISSUE THREAD

**Issue by davidspiess** [feimosi/baguetteBox.js#55]
Can you update to the newest version?
Maybe combine the gulp `bump-patch` task with `npm publish` to keep it always sync.

**Comment by feimosi** [comment]
Thanks for pointing this out! All that time I was almost sure it's automatically updated in the npm repository based on the Git tags.

**Comment by feimosi** [comment]
I could run `npm publish` with appropriate Gulp tasks, but eventually I decided that it's not safe enough. It's still better to run it manually in case I would make a release by mistake.
