### ISSUE TITLE
Refactor the code

### ISSUE THREAD

**Issue by feimosi** [feimosi/baguetteBox.js#56]

**Comment by XhmikosR** [comment]
What exactly do you have in mind?

I think it would make sense to move the polyfills outside of the main source file and include them on build time.

**Comment by feimosi** [comment]
The script was written several years ago and since then I've gained a lot of new experience. I just wanted to walk through all the code and try to write it in a cleaner and more maintainable way. Also, it should be more open to frameworks integration. I'm going to write an Angular directive using baguetteBox.

**Comment by feimosi** [comment]
Actually the script needs to be **rewritten** for the 2.0 release, so I'm closing this.
