### ISSUE TITLE
Drop support for IE < 11

### ISSUE THREAD

**Issue by feimosi** [feimosi/baguetteBox.js#57]

**Comment by XhmikosR** [comment]
Isn't it a little too soon?

Also, with the polyfills, it's not so big a deal. Correct me if I'm wrong :)

**Comment by feimosi** [comment]
IE 8, 9, 10 market share is currently quite marginal ([stats](http://caniuse.com/usage-table)). What's more, even Microsoft has stopped the support. 
I just wanted to get rid of all the polyfills and workarounds, which take unnecessary space. Everyone who needs to support them can still stay with the 1.x version.

**Comment by XhmikosR** [comment]
Don't get me wrong, I'm all for less code and deps. Personally, I don't support anything less than IE9. We could just do IE 10+.

I guess it's OK since it's a major version bump.

**Comment by XhmikosR** [comment]
BTW, do you plan to release 1.6.0 soon? I'd say with all these fixes and tweaks it's OK and then we can have v2.0 without the polyffils, ESLint, and so on.

**Comment by feimosi** [comment]
Okay, I'll see if I can make it with IE 10 :)

I'll release 1.6.0 soon, then see which issues can be resolved now and which should be postponed to milestone 2.0. After that, we can move with a modern JS setup.

**Comment by feimosi** [comment]
Closed in favor of #167.
