### ISSUE TITLE
Caption box positioning

### ISSUE THREAD

**Issue by joomkit** [feimosi/baguetteBox.js#61]
From the current html output the figcaption is by default full width at the bottom.
It doesnt seem possible to set the width of this to match the width of the image across the bottom
eg https://www.dropbox.com/s/ezhoifb8kmxz13i/Screenshot%202016-02-15%2018.32.10.png?dl=0
Is it possible to add a wrapper to the image in which to target the caption information so that it inherits the same width?

**Comment by feimosi** [comment]
When I was building baguetteBox I also wanted to have captions image-wide, but I could't make it working. I recall there were several issues. If you have an idea of clean solution to that feel free to open a PR.

**Comment by joomkit** [comment]
Yes it is tricky. The only solution i played with conceptually was getting the screen width, the image width, calculating the left viewport space and then 'padding' the caption box. I also toyed with injecting another element into the overlay and applying similar css dynamically......i couldnt get into it deeply enough and in the end went for centre aligned text which in some ways although less readable when there is lots of copy, actually make sense in this case as the lightbox image content is centre aligned and the text is quite short. 

Other than that baguetteBox is great !

**Comment by feimosi** [comment]
Ok, I see. Nonetheless I'd prefer to use only CSS to achieve that, without any JavaScript tricks. If you come into an idea how to do that, feel free to reopen the issue. Maybe modern CSS makes it possible, so I could include it in the next major release.
Anyway I'm glad you like baguetteBox :)
