### ISSUE TITLE
delegete / link selector

### ISSUE THREAD

**Issue by CanRau** [feimosi/baguetteBox.js#63]
Hey, thank you for your nice work!

What about something similar to MagnificPopups delegate option?
It's used to tell which links are used to open the modal.
So you can have
baguetteBox.run('.gallery', {
  delegate: '.modal'
});
so only links with "modal" class are considered within gallery (of course still checked if any image is present)
so you could have some image excluded, think this would be nice :)

**Comment by feimosi** [comment]
Hey! 
Actually you can achieve that with `filter` option. I know it's not exactly the same as you're constrained to the `href` attribute but it gives some decent flexibility if you properly manipulate image URLs.

**Comment by CanRau** [comment]
Interesting!
What do you mean by "properly manipulate image URLs" ?
Maybe the filter could accept a function where you can choose where to filter..?
But for now I'm fine with it, was more like a thought I wanted to share.. ;)

**Comment by feimosi** [comment]
I meant that you could use URL parameters like `some.jpg?visible` what wouldn't affect the image loading request. 
Anyway thanks for your suggestion. Maybe in future releases :)

**Comment by CanRau** [comment]
Sure, good to know thanks!
