### ISSUE TITLE
Dynamically added images kill the script

### ISSUE THREAD

**Issue by ffd8** [feimosi/baguetteBox.js#65]
Fantastic, minimal, very nicely designed script here!

Just running into one annoying bug.. it seems to be breaking when using on a page where the images within the '.gallery' div grow dynamically. I'm building a sort of drag + drop image displaying tool and the script works great for contents already in the gallery.. but the minute I add a new content and try to click on something I get this error in the log: 

[Error] NotFoundError: DOM Exception 8: An attempt was made to reference a Node in a context where it does not exist.
	removeChild (baguetteBox.min.js, line 7:3867)
	onload (baguetteBox.min.js, line 7:3867)

I'm trying to do the baguetteBox.run() code on each time I load new contents.. (probably wrong) also tried first destroying it then re-running it to no avail. Also tested turning 'async' on, but no go. With another lightbox or lytebox, I recall being able to simply re-init the thing with new contents coming in– however your design is really elegant and jquery-free! Any tips? or something obvious I'm missing?

**Comment by feimosi** [comment]
I'm really glad you like baguetteBox. 
Indeed it's not prepared for dynamic content. On initialisation it goes through all images inside the gallery and binds appropriate event handlers. It'd be cumbersome to check every time whether the content has changed or not. 
Nonetheless rerunning the script should do the trick (just as a workaround). It's strange to hear it's not. Are you sure, that you're destroying the same gallery? Does it throw anything to the console after being destroyed? When you click the images do they still work?

**Comment by alexdrimbe** [comment]
Hello feimosi, thank you for your great script. 
I had the same issue with dynamic content. I've made some changes in the script and now it should work. Here is the pull request: https://github.com/feimosi/baguetteBox.js/pull/69

**Comment by feimosi** [comment]
Fixed by #93
