### ISSUE TITLE
Trigger display from another element

### ISSUE THREAD

**Issue by RomainSauvaire** [feimosi/baguetteBox.js#67]
Hello @feimosi , congrats for this nice piece of code ! I meant it, simple, responsive and touch friendly :+1: 

I'm trying to trigger the display of the overlay + first image on click on another element (completely outside of the gallery element).

I have tried, with the help of jQuery
```
$('.item').first().trigger('click');
```

with no success. Do you have any tip or idea to do that ? 

Thank you for your help.

**Comment by feimosi** [comment]
Hi, to be sure, do you click on the `<a>` tag element? That is to say, is `.item` class attached to that tag (not `img`). Does dev tools console throw any errors?

**Comment by RomainSauvaire** [comment]
Hello and thank you for the quick answer.

The element I trigger the click on is the `<a>` for sure.

```HTML
<div class="ad_pictures clearfix flex-images gallery">
    <a class="item" href="originals/88/0.jpg" data-w="155" data-h="97" data-at-450="originals/88/0.jpg" data-at-800="originals/88/0.jpg">
        <img src="originals/88/0.jpg" data-target="0.jpg" alt="iPad Air 2 64gb" height="155" width="155">
    </a>
    ...
</div>
```

**Comment by feimosi** [comment]
I've got a suspicion that `.trigger()` may only work for events attached by jQuery. At least that's what docs say. Could you please try using standard [click()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click) method from HTML API?

**Comment by RomainSauvaire** [comment]
Perfect @feimosi , completely forgot to test it. Thank you
