### ISSUE TITLE
Add download image option

### ISSUE THREAD

**Issue by jackiboy** [feimosi/baguetteBox.js#68]
Hi. 
I don't know if this is the right place to post this. 

Would it be possible to add a download option to the gallery? where a user could click a download button and it would download a full resolution image defined for E.g. data-download="{{path to high resolution 4K PNG image}}"

I currently have some 4k resolution artwork that I don't want to load when you open the gallery but instead provide a download button linking to it.

Cheers,
Jack

P.S This plugin is great!

**Comment by feimosi** [comment]
Hi,
Currently there's no dedicated option for that, but you can always make you own button and place it inside the `data-caption` attribute. It'll be injected below the image as a valid HTML code.

Cheers,
Marek

**Comment by jackiboy** [comment]
hmmm did not think of that. That's a great idea!
Cheers,
Jack
