### ISSUE TITLE
Buttons don't show up on Windows 10

### ISSUE THREAD

**Issue by XhmikosR** [feimosi/baguetteBox.js#78]
So this is weird :/ In my main OS, Windows 10 64-bit, the buttons don't show up in auto mode.

On my Windows 7 VM they show up. Something must be different in the touch detection.

**Comment by XhmikosR** [comment]
I was right. So apparently on Windows 10

```
'ontouchstart' in window: true
```

Note that I don't have any touch devices connected :/

**Comment by XhmikosR** [comment]
OK, something weird is happening with Firefox. Internet Explorer works normally.

I'm goona close this, but it's weird nevertheless. Might have something to do with FF dev tools enabling touch events when the dev toolbar is open https://bugzilla.mozilla.org/show_bug.cgi?id=970346.

**Comment by feimosi** [comment]
Yeah, hopefully it's a Firefox issue.
