### ISSUE TITLE
Page jump when the first image is opened

### ISSUE THREAD

**Issue by XhmikosR** [feimosi/baguetteBox.js#80]
Since a video is better than words, attached is a demonstration.

https://dl.dropboxusercontent.com/u/3607425/2016-03-29_18-16-45.mp4

My browser is Firefox 46.0b5 on Windows x64 but I see the same with Microsoft Edge.

Settings:

```js
baguetteBox.run(selector, {
    async: false,
    buttons: "auto",
    noScrollbars: true
});
```

The code if you cannot reproduce this is in this branch here https://github.com/mpc-hc/mpc-hc.org/compare/baguetteBox.js

**Comment by feimosi** [comment]
I'll look into that soon. I believe it doesn't happen on Chrome? Have you tried manipulating the options? I got a feeling it may be something with scrollbars.

**Comment by XhmikosR** [comment]
It doesn't happen when testing locally, so I can't really debug it without putting it live.

I will try again later with Chrome and let you know, but I have the same feeling that it's because of the scrollbars. Still shouldn't happen :).

**Comment by XhmikosR** [comment]
OK, it happens with Chrome too.

**Comment by feimosi** [comment]
Ok, got it. Still, how is it possible it doesn't show up locally, strange.

**Comment by XhmikosR** [comment]
And `noScrollbars` isn't to blame. I tried without it too.

**Comment by feimosi** [comment]
I assume you're using the 1.5.0 version without any modifications? Does the [demo page](https://feimosi.github.io/baguetteBox.js/) work for you?

**Comment by XhmikosR** [comment]
I even try `preload: 0` and still the same jump, it's just one. So the jump happens while the image is being loaded.

**Comment by XhmikosR** [comment]
I'm using the latest master, but I tried 1.5.0 and still the same results.

**Comment by feimosi** [comment]
Ok, I see, then it must be probably something with the styles.

**Comment by XhmikosR** [comment]
The reason it might not happen locally can be because locally the image is retrieved instantly so the issue isn't visible, but is still there. I can't think of another explanation.

**Comment by feimosi** [comment]
Maybe, but I don't see the spinner being displayed.

**Comment by XhmikosR** [comment]
OK then I tend more and more to #86

**Comment by XhmikosR** [comment]
Can you quickly implement a fix for that and ping me? I think those selectors are missing due to uncss and the fact that they aren't prefixed with `baguetteBox`.

**Comment by XhmikosR** [comment]
Yup, that was it. So, I'm closing this, sorry for the noise.

It's #86 that needs to be fixed so that my ignore works fine and also there are no conflicts.

**Comment by feimosi** [comment]
I'm glad you've found the problem. I'm merging the fix.
