### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by XhmikosR** [feimosi/baguetteBox.js#82]
With the JS lint tool of your preference, maybe an HTML validator and gulp-accessibility (uses html_codesniffer).

**Comment by feimosi** [comment]
:+1:  Not a bad idea, at least with the linter, gulp-accessibility may not be able to check dynamically generated lightbox overlay.

**Comment by XhmikosR** [comment]
It certainly does ;)

**Comment by XhmikosR** [comment]
That's how I noticed the existent accessibility issues :)

**Comment by feimosi** [comment]
Ok, good to know :)

**Comment by XhmikosR** [comment]
This was fixed by #91. We can improve it later.
