### ISSUE TITLE
baguetteBox.js on cdnjs.com

### ISSUE THREAD

**Issue by tarampampam** [feimosi/baguetteBox.js#85]
Maybe you add package baguetteBox to [cdnjs.com](https://cdnjs.com/)?

It is really easy and will be usefull not only for me

**Comment by feimosi** [comment]
Sounds like a great idea. How is it done? I haven't used [cdnjs](cdnjs.com) yet and the documentation is a bit obscure.

**Comment by tarampampam** [comment]
I think you can do it [here](https://goo.gl/VBLhp9)

**Comment by feimosi** [comment]
Resolved with https://github.com/cdnjs/cdnjs/pull/9016
