### ISSUE TITLE
Move the website to this repo

### ISSUE THREAD

**Issue by XhmikosR** [feimosi/baguetteBox.js#89]
In a new gh-pages branch. The URL will be the same if you keep your https://github.com/feimosi/feimosi.github.io even empty.

**Comment by XhmikosR** [comment]
Correction, I don't think you even need to keep your profile repo after the move.

**Comment by XhmikosR** [comment]
Demonstration http://xhmikosr.github.io/baguetteBox.js

**Comment by feimosi** [comment]
Ok, good idea. I'll take care of that.

**Comment by XhmikosR** [comment]
Just make sure you create an `--orphan` gh-pages branch and then add your files.

Now another thing I was wondering. I'd like to have one dist dir with minified and normal files. But it doesn't make sense to have the html and the other assets there.

So, I suggest we have a docs dir and have a copy gulp task which will copy the files from dist.

**Comment by feimosi** [comment]
`gh-pages` branch is ready. Currently with the 1.5.0 release.

What's the advantage of also keeping unminified versions in dist/ ?

**Comment by XhmikosR** [comment]
Because currently it's messier. The dist dir should have all the dist files, minified and non-minified and let the end user choose what to use.

**Comment by feimosi** [comment]
I'll think about that :+1:

**Comment by XhmikosR** [comment]
I found a regression with IE8, so I'm looking into that. We'll probably need 1.6.1.

Don't forget to update the gh-pages branch later.
