### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by 2aces** [feimosi/baguetteBox.js#98]
In order to improve accessibility, it would be good to use roles and other wai-aria attributes and techniques, alt attribute and other acessibility best practices.

I will fork and provide a first take in this direction.

References:

- [https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_dialog_role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_dialog_role)

- [https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alertdialog_role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alertdialog_role)

- [https://www.w3.org/WAI/GL/wiki/Using_ARIA_role%3Ddialog_to_implement_a_modal_dialog_box](https://www.w3.org/WAI/GL/wiki/Using_ARIA_role%3Ddialog_to_implement_a_modal_dialog_box)

**Comment by XhmikosR** [comment]
We should also add `alt` for the images.

**Comment by 2aces** [comment]
@XhmikosR you're right. I did that in the version I am using on my project and forgot to put it in this issue.
